// flexible-graphrag-ui/frontend-vue/src/components/sources/FileUploadForm.vue
<template>
  <BaseSourceForm
    title="File Upload"
    description="Upload documents directly from your computer"
  >
    <v-card
      :class="[
        'pa-6 mb-4 text-center cursor-pointer',
        isDragOver ? 'drag-over' : 'drag-normal'
      ]"
      :style="dropZoneStyle"
      @drop="handleFileDrop"
      @dragover="handleDragOver"
      @dragenter="handleDragEnter"
      @dragleave="handleDragLeave"
      @click="() => fileInputRef?.click()"
    >
      <h3 class="mb-2" :style="{ color: '#ffffff' }">
        Drop files here or click to select
      </h3>
      <p :style="{ color: '#ffffff' }">
        Supports: PDF, DOCX, XLSX, PPTX, TXT, MD, HTML, CSV, PNG, JPG
      </p>
      <input
        ref="fileInputRef"
        type="file"
        multiple
        accept=".pdf,.docx,.xlsx,.pptx,.txt,.md,.html,.csv,.png,.jpg,.jpeg"
        @change="handleFileSelect"
        style="display: none"
      />
    </v-card>

    <!-- Selected Files Display -->
    <div v-if="selectedFiles.length > 0" class="mb-4">
      <h4 class="mb-2">Selected Files ({{ selectedFiles.length }}):</h4>
      <v-card
        v-for="(file, index) in selectedFiles"
        :key="index"
        class="pa-3 mb-2"
        variant="outlined"
      >
        <div class="d-flex align-center justify-space-between">
          <div>
            <div class="font-weight-medium">{{ file.name }}</div>
            <div class="text-caption text-medium-emphasis">{{ formatFileSize(file.size) }}</div>
          </div>
          <v-btn
            color="error"
            variant="text"
            size="small"
            @click="removeFile(index)"
          >
            Remove
          </v-btn>
        </div>
      </v-card>
    </div>
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, ref, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'FileUploadForm',
  components: {
    BaseSourceForm
  },
  props: {
    selectedFiles: {
      type: Array as () => File[],
      default: () => []
    }
  },
  emits: ['update:selectedFiles', 'configuration-change', 'validation-change'],
  setup(props, { emit }) {
    const isDragOver = ref(false);
    const fileInputRef = ref<HTMLInputElement>();

    const dropZoneStyle = computed(() => ({
      border: isDragOver.value ? '2px solid #ffffff' : '2px dashed #ffffff',
      backgroundColor: isDragOver.value ? '#000000' : '#1976d2',
      transition: 'all 0.2s ease-in-out',
    }));

    const isValid = computed(() => {
      return props.selectedFiles.length > 0;
    });

    const config = computed(() => ({
      files: props.selectedFiles
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const formatFileSize = (bytes: number): string => {
      if (bytes < 1024) {
        return bytes === 0 ? "0 B" : "1 KB";
      } else if (bytes < 1024 * 1024) {
        return `${Math.ceil(bytes / 1024)} KB`;
      } else {
        return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
      }
    };

    const handleFileSelect = (event: Event) => {
      const target = event.target as HTMLInputElement;
      const files = target.files;
      if (files) {
        requestAnimationFrame(() => {
          emit('update:selectedFiles', Array.from(files));
          target.value = '';
        });
      }
    };

    const handleFileDrop = (event: DragEvent) => {
      event.preventDefault();
      event.stopPropagation();
      isDragOver.value = false;
      
      const files = event.dataTransfer?.files;
      if (files) {
        requestAnimationFrame(() => {
          emit('update:selectedFiles', Array.from(files));
        });
      }
    };

    const handleDragOver = (event: DragEvent) => {
      event.preventDefault();
      event.stopPropagation();
      if (event.dataTransfer) {
        event.dataTransfer.dropEffect = 'copy';
      }
    };

    const handleDragEnter = (event: DragEvent) => {
      event.preventDefault();
      event.stopPropagation();
      isDragOver.value = true;
      if (event.dataTransfer) {
        event.dataTransfer.dropEffect = 'copy';
      }
    };

    const handleDragLeave = (event: DragEvent) => {
      event.preventDefault();
      event.stopPropagation();
      
      const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
      const x = event.clientX;
      const y = event.clientY;
      
      if (x < rect.left || x > rect.right || y < rect.top || y > rect.bottom) {
        isDragOver.value = false;
      }
    };

    const removeFile = (index: number) => {
      const newFiles = props.selectedFiles.filter((_, i) => i !== index);
      emit('update:selectedFiles', newFiles);
    };

    return {
      isDragOver,
      fileInputRef,
      dropZoneStyle,
      formatFileSize,
      handleFileSelect,
      handleFileDrop,
      handleDragOver,
      handleDragEnter,
      handleDragLeave,
      removeFile,
    };
  },
});
</script>

<style scoped>
.cursor-pointer {
  cursor: pointer;
}

.drag-normal {
  background-color: #1976d2 !important;
}
</style>

// flexible-graphrag-ui/frontend-react/src/components/sources/FileUploadForm.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { Box, Typography, Button } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface FileUploadFormProps extends BaseSourceFormProps {
  selectedFiles: File[];
  onSelectedFilesChange: (files: File[]) => void;
}

export const FileUploadForm: React.FC<FileUploadFormProps> = ({
  currentTheme,
  selectedFiles,
  onSelectedFilesChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const [isDragOver, setIsDragOver] = useState<boolean>(false);

  const isValid = useMemo(() => {
    return selectedFiles.length > 0;
  }, [selectedFiles.length]);

  const config = useMemo(() => ({
    files: selectedFiles
  }), [selectedFiles]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  // File size formatting
  const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) {
      return bytes === 0 ? "0 B" : "1 KB";
    } else if (bytes < 1024 * 1024) {
      return `${Math.ceil(bytes / 1024)} KB`;
    } else {
      return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
    }
  };

  // File handling
  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (files) {
      requestAnimationFrame(() => {
        const fileArray = Array.from(files);
        onSelectedFilesChange(fileArray);
        event.target.value = '';
      });
    }
  };

  const handleFileDrop = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDragOver(false);
    
    const files = event.dataTransfer.files;
    if (files) {
      requestAnimationFrame(() => {
        const fileArray = Array.from(files);
        onSelectedFilesChange(fileArray);
      });
    }
  };

  const handleDragOver = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'copy';
    }
  };

  const handleDragEnter = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDragOver(true);
    
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'copy';
    }
  };

  const handleDragLeave = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    
    const rect = event.currentTarget.getBoundingClientRect();
    const x = event.clientX;
    const y = event.clientY;
    
    if (x < rect.left || x > rect.right || y < rect.top || y > rect.bottom) {
      setIsDragOver(false);
    }
  };

  const removeFile = (index: number) => {
    onSelectedFilesChange(selectedFiles.filter((_, i) => i !== index));
  };

  return (
    <BaseSourceForm
      title="File Upload"
      description="Upload documents directly from your computer"
    >
      <Box
        sx={{
          border: isDragOver ? '2px solid #ffffff' : '2px dashed #ffffff',
          borderRadius: 2,
          p: 3,
          textAlign: 'center',
          cursor: 'pointer',
          backgroundColor: isDragOver ? '#000000' : '#1976d2',
          transition: 'all 0.2s ease-in-out',
        }}
        onDrop={handleFileDrop}
        onDragOver={handleDragOver}
        onDragEnter={handleDragEnter}
        onDragLeave={handleDragLeave}
        onClick={() => document.getElementById('file-input')?.click()}
      >
        <Typography variant="h6" gutterBottom sx={{ color: '#ffffff' }}>
          Drop files here or click to select
        </Typography>
        <Typography variant="body2" sx={{ color: '#ffffff' }}>
          Supports: PDF, DOCX, XLSX, PPTX, TXT, MD, HTML, CSV, PNG, JPG
        </Typography>
        <input
          id="file-input"
          type="file"
          multiple
          accept=".pdf,.docx,.xlsx,.pptx,.txt,.md,.html,.csv,.png,.jpg,.jpeg"
          onChange={handleFileSelect}
          aria-label="Select files to upload"
          style={{ display: 'none' }}
        />
      </Box>
      
      {selectedFiles.length > 0 && (
        <Box sx={{ mt: 2 }}>
          <Typography variant="subtitle2" gutterBottom>
            Selected Files ({selectedFiles.length}):
          </Typography>
          {selectedFiles.map((file, index) => (
            <Box key={index} sx={{ 
              display: 'flex', 
              alignItems: 'center', 
              justifyContent: 'space-between',
              p: 1,
              border: `1px solid ${currentTheme.palette.divider}`,
              borderRadius: 1,
              mb: 1
            }}>
              <Box>
                <Typography variant="body2">{file.name}</Typography>
                <Typography variant="caption" color="text.secondary">
                  {formatFileSize(file.size)}
                </Typography>
              </Box>
              <Button
                size="small"
                color="error"
                onClick={() => removeFile(index)}
              >
                Remove
              </Button>
            </Box>
          ))}
        </Box>
      )}
    </BaseSourceForm>
  );
};
