// flexible-graphrag-ui/frontend-vue/src/components/sources/GoogleDriveSourceForm.vue
<template>
  <BaseSourceForm
    title="Google Drive"
    description="Connect to Google Drive using service account credentials"
  >
    <v-textarea
      :model-value="credentials"
      @update:model-value="handleCredentialsChange"
      label="Service Account Credentials (JSON) *"
      variant="outlined"
      class="mb-2"
      placeholder='{"type": "service_account", "project_id": "...", ...}'
      hint="JSON service account key (required)"
      persistent-hint
      rows="4"
      required
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'GoogleDriveSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    credentials: {
      type: String,
      default: ''
    }
  },
  emits: ['update:credentials', 'configuration-change', 'validation-change'],
  setup(props, { emit }) {
    const isValid = computed(() => {
      return props.credentials.trim() !== '';
    });

    const config = computed(() => ({
      credentials: props.credentials
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleCredentialsChange = (value: string) => {
      emit('update:credentials', value);
    };

    return {
      handleCredentialsChange,
    };
  },
});
</script>

// flexible-graphrag-ui/frontend-react/src/components/sources/GoogleDriveSourceForm.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { TextField } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface GoogleDriveSourceFormProps extends BaseSourceFormProps {
  credentials: string;
  onCredentialsChange: (credentials: string) => void;
}

export const GoogleDriveSourceForm: React.FC<GoogleDriveSourceFormProps> = ({
  currentTheme,
  credentials,
  onCredentialsChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const [folderId, setFolderId] = useState<string>('');

  const isValid = useMemo(() => {
    return credentials.trim() !== '';
  }, [credentials]);

  const config = useMemo(() => ({
    credentials: credentials,
    folder_id: folderId || undefined
  }), [credentials, folderId]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  return (
    <BaseSourceForm
      title="Google Drive"
      description="Connect to Google Drive using service account credentials"
    >
      <TextField
        fullWidth
        label="Folder ID (Optional)"
        variant="outlined"
        value={folderId}
        onChange={(e) => setFolderId(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"
        helperText="Optional: Google Drive folder ID to process specific folder. Leave empty to process all accessible files."
      />
      <TextField
        fullWidth
        label="Service Account Credentials (JSON)"
        variant="outlined"
        value={credentials}
        onChange={(e) => onCredentialsChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        multiline
        rows={3}
        placeholder='{"type": "service_account", "project_id": "...", ...}'
        helperText="Paste your Google Drive service account JSON credentials"
      />
    </BaseSourceForm>
  );
};
