// flexible-graphrag-ui/frontend-angular/projects/flexible-graphrag-angular-lib/src/lib/components/sources/onedrive-source-form.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';

export interface OneDriveSourceConfig {
  user_principal_name: string;
  client_id: string;
  client_secret: string;
  tenant_id: string;
  folder_path?: string;
  folder_id?: string;
}

@Component({
  selector: 'app-onedrive-source-form',
  template: `
    <app-base-source-form 
      title="Microsoft OneDrive" 
      description="Connect to OneDrive using Azure app registration credentials">
      
      <div class="form-row">
        <mat-form-field appearance="outline" class="half-width">
          <mat-label>User Principal Name *</mat-label>
          <input matInput
                 [(ngModel)]="userPrincipalName"
                 (ngModelChange)="onUserPrincipalNameChange()"
                 placeholder="user@domain.com"
                 required />
          <mat-hint>User principal name (email)</mat-hint>
        </mat-form-field>

        <mat-form-field appearance="outline" class="half-width">
          <mat-label>Client ID *</mat-label>
          <input matInput
                 [(ngModel)]="clientId"
                 (ngModelChange)="onClientIdChange()"
                 placeholder="12345678-1234-1234-1234-123456789012"
                 required />
        </mat-form-field>
      </div>

      <div class="form-row">
        <mat-form-field appearance="outline" class="half-width">
          <mat-label>Client Secret *</mat-label>
          <input matInput
                 type="password"
                 [(ngModel)]="clientSecret"
                 (ngModelChange)="onClientSecretChange()"
                 required />
        </mat-form-field>

        <mat-form-field appearance="outline" class="half-width">
          <mat-label>Tenant ID *</mat-label>
          <input matInput
                 [(ngModel)]="tenantId"
                 (ngModelChange)="onTenantIdChange()"
                 placeholder="common or tenant-id"
                 required />
        </mat-form-field>
      </div>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Folder Path (Optional)</mat-label>
        <input matInput
               [(ngModel)]="folderPath"
               (ngModelChange)="onFolderPathChange()"
               placeholder="/Documents/Reports" />
        <mat-hint>Optional: specific folder path in OneDrive</mat-hint>
      </mat-form-field>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Folder ID (Optional)</mat-label>
        <input matInput
               [(ngModel)]="folderId"
               (ngModelChange)="onFolderIdChange()"
               placeholder="01BYE5RZ6QN6OWWLQZC5FK2GWWDURNZHIL" />
        <mat-hint>Optional: specific OneDrive folder ID</mat-hint>
      </mat-form-field>
    </app-base-source-form>
  `,
  styles: [`
    .full-width {
      width: 100%;
      margin-bottom: 16px;
    }
    
    .form-row {
      display: flex;
      gap: 16px;
      margin-bottom: 16px;
    }
    
    .half-width {
      flex: 1;
    }
  `],
  standalone: false
})
export class OneDriveSourceFormComponent implements OnInit, OnDestroy {
  @Input() userPrincipalName: string = '';
  @Input() clientId: string = '';
  @Input() clientSecret: string = '';
  @Input() tenantId: string = '';
  
  @Output() userPrincipalNameChange = new EventEmitter<string>();
  @Output() clientIdChange = new EventEmitter<string>();
  @Output() clientSecretChange = new EventEmitter<string>();
  @Output() tenantIdChange = new EventEmitter<string>();
  @Output() configurationChange = new EventEmitter<OneDriveSourceConfig>();
  @Output() validationChange = new EventEmitter<boolean>();

  folderPath: string = '';
  folderId: string = '';

  ngOnInit() {
    this.updateValidationAndConfig();
  }

  ngOnDestroy() {
    // Cleanup if needed
  }

  private updateValidationAndConfig() {
    const isValid = this.userPrincipalName.trim() !== '' && 
                   this.clientId.trim() !== '' && 
                   this.clientSecret.trim() !== '' && 
                   this.tenantId.trim() !== '';
    
    const config: OneDriveSourceConfig = {
      user_principal_name: this.userPrincipalName,
      client_id: this.clientId,
      client_secret: this.clientSecret,
      tenant_id: this.tenantId,
      folder_path: this.folderPath || undefined,
      folder_id: this.folderId || undefined
    };
    
    this.validationChange.emit(isValid);
    this.configurationChange.emit(config);
  }

  onUserPrincipalNameChange(): void {
    this.userPrincipalNameChange.emit(this.userPrincipalName);
    this.updateValidationAndConfig();
  }

  onClientIdChange(): void {
    this.clientIdChange.emit(this.clientId);
    this.updateValidationAndConfig();
  }

  onClientSecretChange(): void {
    this.clientSecretChange.emit(this.clientSecret);
    this.updateValidationAndConfig();
  }

  onTenantIdChange(): void {
    this.tenantIdChange.emit(this.tenantId);
    this.updateValidationAndConfig();
  }

  onFolderPathChange(): void {
    this.updateValidationAndConfig();
  }

  onFolderIdChange(): void {
    this.updateValidationAndConfig();
  }
}

// flexible-graphrag-ui/frontend-react/src/components/sources/OneDriveSourceForm.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { TextField, Box } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface OneDriveSourceFormProps extends BaseSourceFormProps {
  userPrincipalName: string;
  clientId: string;
  clientSecret: string;
  tenantId: string;
  onUserPrincipalNameChange: (userPrincipalName: string) => void;
  onClientIdChange: (clientId: string) => void;
  onClientSecretChange: (clientSecret: string) => void;
  onTenantIdChange: (tenantId: string) => void;
}

export const OneDriveSourceForm: React.FC<OneDriveSourceFormProps> = ({
  currentTheme: _currentTheme,
  userPrincipalName,
  clientId,
  clientSecret,
  tenantId,
  onUserPrincipalNameChange,
  onClientIdChange,
  onClientSecretChange,
  onTenantIdChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const [folderPath, setFolderPath] = useState('');
  const [folderId, setFolderId] = useState('');

  const isValid = useMemo(() => {
    return userPrincipalName.trim() !== '' && clientId.trim() !== '' && clientSecret.trim() !== '' && tenantId.trim() !== '';
  }, [userPrincipalName, clientId, clientSecret, tenantId]);

  const config = useMemo(() => ({
    user_principal_name: userPrincipalName,
    client_id: clientId,
    client_secret: clientSecret,
    tenant_id: tenantId,
    folder_path: folderPath || undefined,
    folder_id: folderId || undefined
  }), [userPrincipalName, clientId, clientSecret, tenantId, folderPath, folderId]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  return (
    <BaseSourceForm
      title="Microsoft OneDrive"
      description="Connect to OneDrive using Azure app registration credentials"
    >
      <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
        <TextField
          fullWidth
          label="User Principal Name *"
          variant="outlined"
          value={userPrincipalName}
          onChange={(e) => onUserPrincipalNameChange(e.target.value)}
          size="small"
          placeholder="user@domain.com"
          helperText="User principal name (email)"
          required
        />
        <TextField
          fullWidth
          label="Client ID *"
          variant="outlined"
          value={clientId}
          onChange={(e) => onClientIdChange(e.target.value)}
          size="small"
          placeholder="12345678-1234-1234-1234-123456789012"
          required
        />
      </Box>
      <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
        <TextField
          fullWidth
          label="Client Secret *"
          variant="outlined"
          value={clientSecret}
          onChange={(e) => onClientSecretChange(e.target.value)}
          size="small"
          type="password"
          required
        />
        <TextField
          fullWidth
          label="Tenant ID *"
          variant="outlined"
          value={tenantId}
          onChange={(e) => onTenantIdChange(e.target.value)}
          size="small"
          placeholder="common or tenant-id"
          required
        />
      </Box>
      <TextField
        fullWidth
        label="Folder Path (Optional)"
        variant="outlined"
        value={folderPath}
        onChange={(e) => setFolderPath(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="/Documents/Reports"
        helperText="Optional: specific folder path in OneDrive"
      />
      <TextField
        fullWidth
        label="Folder ID (Optional)"
        variant="outlined"
        value={folderId}
        onChange={(e) => setFolderId(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="01BYE5RZ6QN6OWWLQZC5FK2GWWDURNZHIL"
        helperText="Optional: specific OneDrive folder ID"
      />
    </BaseSourceForm>
  );
};
