// flexible-graphrag-ui/frontend-angular/projects/flexible-graphrag-angular-lib/src/lib/components/sources/sharepoint-source-form.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';

export interface SharePointSourceConfig {
  client_id: string;
  client_secret: string;
  tenant_id: string;
  site_name: string;
  site_id?: string;
  folder_path?: string;
  folder_id?: string;
}

@Component({
  selector: 'app-sharepoint-source-form',
  template: `
    <app-base-source-form 
      title="Microsoft SharePoint" 
      description="Connect to SharePoint using Azure app registration credentials">
      
      <div class="form-row">
        <mat-form-field appearance="outline" class="half-width">
          <mat-label>Client ID *</mat-label>
          <input matInput
                 [(ngModel)]="clientId"
                 (ngModelChange)="onClientIdChange()"
                 placeholder="12345678-1234-1234-1234-123456789012"
                 required
                 autocomplete="off" />
          <mat-hint>Azure app registration client ID</mat-hint>
        </mat-form-field>

        <mat-form-field appearance="outline" class="half-width">
          <mat-label>Tenant ID *</mat-label>
          <input matInput
                 [(ngModel)]="tenantId"
                 (ngModelChange)="onTenantIdChange()"
                 placeholder="87654321-4321-4321-4321-210987654321"
                 required
                 autocomplete="off" />
          <mat-hint>Azure tenant ID</mat-hint>
        </mat-form-field>
      </div>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Client Secret *</mat-label>
        <input matInput
               type="password"
               [(ngModel)]="clientSecret"
               (ngModelChange)="onClientSecretChange()"
               required
               autocomplete="off" />
        <mat-hint>Azure app registration client secret</mat-hint>
      </mat-form-field>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Site Name *</mat-label>
        <input matInput
               [(ngModel)]="siteName"
               (ngModelChange)="onSiteNameChange()"
               placeholder="mysite"
               required />
        <mat-hint>SharePoint site name (required)</mat-hint>
      </mat-form-field>

      <div class="form-row">
        <mat-form-field appearance="outline" class="half-width">
          <mat-label>Folder Path</mat-label>
          <input matInput
                 [(ngModel)]="folderPath"
                 (ngModelChange)="onFolderPathChange()"
                 placeholder="/Shared Documents/Reports" />
          <mat-hint>Optional: folder path within site</mat-hint>
        </mat-form-field>

        <mat-form-field appearance="outline" class="half-width">
          <mat-label>Folder ID</mat-label>
          <input matInput
                 [(ngModel)]="folderId"
                 (ngModelChange)="onFolderIdChange()"
                 placeholder="01BYE5RZ6QN6OWWLQZC5FK2GWWDURNZHIL" />
          <mat-hint>Optional: SharePoint folder ID</mat-hint>
        </mat-form-field>
      </div>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Site ID (Optional)</mat-label>
        <input matInput
               [(ngModel)]="siteId"
               (ngModelChange)="onSiteIdChange()"
               placeholder="12345678-1234-1234-1234-123456789012" />
        <mat-hint>Optional: for Sites.Selected permission</mat-hint>
      </mat-form-field>
    </app-base-source-form>
  `,
  styles: [`
    .full-width {
      width: 100%;
      margin-bottom: 16px;
    }
    
    .form-row {
      display: flex;
      gap: 16px;
      margin-bottom: 16px;
    }
    
    .half-width {
      flex: 1;
    }
  `],
  standalone: false
})
export class SharePointSourceFormComponent implements OnInit, OnDestroy {
  @Input() siteName: string = '';
  
  @Output() siteNameChange = new EventEmitter<string>();
  @Output() configurationChange = new EventEmitter<SharePointSourceConfig>();
  @Output() validationChange = new EventEmitter<boolean>();

  clientId: string = '';
  clientSecret: string = '';
  tenantId: string = '';
  folderPath: string = '';
  folderId: string = '';
  siteId: string = '';

  ngOnInit() {
    this.updateValidationAndConfig();
  }

  ngOnDestroy() {
    // Cleanup if needed
  }

  private updateValidationAndConfig() {
    const isValid = this.clientId.trim() !== '' && 
                   this.clientSecret.trim() !== '' && 
                   this.tenantId.trim() !== '' && 
                   this.siteName.trim() !== '';
    
    const config: SharePointSourceConfig = {
      client_id: this.clientId,
      client_secret: this.clientSecret,
      tenant_id: this.tenantId,
      site_name: this.siteName,
      site_id: this.siteId || undefined,
      folder_path: this.folderPath || undefined,
      folder_id: this.folderId || undefined
    };
    
    this.validationChange.emit(isValid);
    this.configurationChange.emit(config);
  }

  onClientIdChange(): void {
    this.updateValidationAndConfig();
  }

  onClientSecretChange(): void {
    this.updateValidationAndConfig();
  }

  onTenantIdChange(): void {
    this.updateValidationAndConfig();
  }

  onSiteNameChange(): void {
    this.siteNameChange.emit(this.siteName);
    this.updateValidationAndConfig();
  }

  onFolderPathChange(): void {
    this.updateValidationAndConfig();
  }

  onFolderIdChange(): void {
    this.updateValidationAndConfig();
  }

  onSiteIdChange(): void {
    this.updateValidationAndConfig();
  }
}

// flexible-graphrag-ui/frontend-react/src/components/sources/SharePointSourceForm.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { TextField, Box } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface SharePointSourceFormProps extends BaseSourceFormProps {
  siteName: string;
  clientId: string;
  clientSecret: string;
  tenantId: string;
  onSiteNameChange: (siteName: string) => void;  // Changed from onSiteUrlChange
  onClientIdChange: (clientId: string) => void;
  onClientSecretChange: (clientSecret: string) => void;
  onTenantIdChange: (tenantId: string) => void;
}

export const SharePointSourceForm: React.FC<SharePointSourceFormProps> = ({
  currentTheme,
  siteName,  // Changed from siteUrl to siteName
  clientId,
  clientSecret,
  tenantId,
  onSiteNameChange,  // Changed from onSiteUrlChange
  onClientIdChange,
  onClientSecretChange,
  onTenantIdChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const [folderPath, setFolderPath] = useState('');
  const [folderId, setFolderId] = useState('');  // Changed from documentLibrary to folderId
  const [siteId, setSiteId] = useState('');  // Added for Sites.Selected permission

  const isValid = useMemo(() => {
    return siteName.trim() !== '' && clientId.trim() !== '' && clientSecret.trim() !== '' && tenantId.trim() !== '';
  }, [siteName, clientId, clientSecret, tenantId]);

  const config = useMemo(() => ({
    site_name: siteName,
    client_id: clientId,
    client_secret: clientSecret,
    tenant_id: tenantId,
    site_id: siteId || undefined,  // Added for Sites.Selected permission
    folder_path: folderPath || undefined,
    folder_id: folderId || undefined  // Changed from document_library to folder_id
  }), [siteName, clientId, clientSecret, tenantId, siteId, folderPath, folderId]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  return (
    <BaseSourceForm
      title="Microsoft SharePoint"
      description="Connect to SharePoint sites using Azure app registration credentials"
    >
      <TextField
        fullWidth
        label="Site Name *"
        variant="outlined"
        value={siteName}
        onChange={(e) => onSiteNameChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="sitename"
        helperText="SharePoint site name (not full URL, just the site name)"
        required
        autoComplete="off"
      />
      <TextField
        fullWidth
        label="Site ID (Optional)"
        variant="outlined"
        value={siteId}
        onChange={(e) => setSiteId(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="12345678-1234-1234-1234-123456789012"
        helperText="Optional: Site ID for Sites.Selected permission (recommended for security)"
        autoComplete="off"
      />
      <TextField
        fullWidth
        label="Client ID *"
        variant="outlined"
        value={clientId}
        onChange={(e) => onClientIdChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="12345678-1234-1234-1234-123456789012"
        required
      />
      <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
        <TextField
          fullWidth
          label="Client Secret *"
          variant="outlined"
          value={clientSecret}
          onChange={(e) => onClientSecretChange(e.target.value)}
          size="small"
          type="password"
          required
        />
        <TextField
          fullWidth
          label="Tenant ID *"
          variant="outlined"
          value={tenantId}
          onChange={(e) => onTenantIdChange(e.target.value)}
          size="small"
          placeholder="tenant-id"
          required
        />
      </Box>
      <TextField
        fullWidth
        label="Folder ID (Optional)"
        variant="outlined"
        value={folderId}
        onChange={(e) => setFolderId(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="01BYE5RZ6QN6OWWLQZC5FK2GWWDURNZHIL"
        helperText="Optional: specific folder ID (replaces document library)"
        autoComplete="off"
      />
      <TextField
        fullWidth
        label="Folder Path (Optional)"
        variant="outlined"
        value={folderPath}
        onChange={(e) => setFolderPath(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="/Shared Documents/Reports"
        helperText="Optional: specific folder path within site"
        autoComplete="off"
      />
    </BaseSourceForm>
  );
};
