// flexible-graphrag-ui/frontend-vue/src/components/sources/WebSourceForm.vue
<template>
  <BaseSourceForm
    title="Web Page"
    description="Extract content from any web page"
  >
    <v-text-field
      :model-value="url"
      @update:model-value="handleUrlChange"
      label="Website URL"
      variant="outlined"
      class="mb-2"
      placeholder="https://example.com"
      hint="Enter a valid website URL to extract content from"
      persistent-hint
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'WebSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    url: {
      type: String,
      default: ''
    }
  },
  emits: ['update:url', 'configuration-change', 'validation-change'],
  setup(props, { emit }) {
    const isValid = computed(() => {
      return props.url.trim() !== '' && props.url.startsWith('http');
    });

    const config = computed(() => ({
      url: props.url
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleUrlChange = (value: string) => {
      emit('update:url', value);
    };

    return {
      handleUrlChange,
    };
  },
});
</script>

// flexible-graphrag-ui/frontend-react/src/components/sources/WebSourceForm.tsx
import React, { useEffect, useMemo } from 'react';
import { TextField } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface WebSourceFormProps extends BaseSourceFormProps {
  url: string;
  onUrlChange: (url: string) => void;
}

export const WebSourceForm: React.FC<WebSourceFormProps> = ({
  currentTheme,
  url,
  onUrlChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const isValid = useMemo(() => {
    return url.trim() !== '' && url.startsWith('http');
  }, [url]);

  const config = useMemo(() => ({
    url: url
  }), [url]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  return (
    <BaseSourceForm
      title="Web Page"
      description="Extract content from any web page"
    >
      <TextField
        fullWidth
        label="Website URL"
        variant="outlined"
        value={url}
        onChange={(e) => onUrlChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="https://example.com"
        helperText="Enter a valid website URL to extract content from"
      />
    </BaseSourceForm>
  );
};
