// flexible-graphrag-ui/frontend-react/src/components/SearchTab.tsx
import React, { useState } from 'react';
import {
  Box,
  Typography,
  Button,
  TextField,
  Paper,
  CircularProgress,
  Tabs,
  Tab,
} from '@mui/material';
import { TabContext, TabPanel } from '@mui/lab';
import { Theme } from '@mui/material/styles';
import axios from 'axios';
import { QueryRequest, ApiResponse, SourceDocument } from '../types/api';
import { SourceDocs, storeLabel } from './SourceDocs';

interface SearchTabProps {
  currentTheme: Theme;
  activeTab: string;
  question: string;
  searchResults: any[];
  qaAnswer: string;
  qaSources: SourceDocument[];
  hasSearched: boolean;
  lastSearchQuery: string;
  isQuerying: boolean;
  onActiveTabChange: (activeTab: string) => void;
  onQuestionChange: (question: string) => void;
  onSearchResultsChange: (results: any[]) => void;
  onQaAnswerChange: (answer: string) => void;
  onQaSourcesChange: (sources: SourceDocument[]) => void;
  onHasSearchedChange: (hasSearched: boolean) => void;
  onLastSearchQueryChange: (query: string) => void;
  onIsQueryingChange: (isQuerying: boolean) => void;
}

export const SearchTab: React.FC<SearchTabProps> = ({ 
  currentTheme,
  activeTab,
  question,
  searchResults,
  qaAnswer,
  qaSources,
  hasSearched,
  lastSearchQuery,
  isQuerying,
  onActiveTabChange,
  onQuestionChange,
  onSearchResultsChange,
  onQaAnswerChange,
  onQaSourcesChange,
  onHasSearchedChange,
  onLastSearchQueryChange,
  onIsQueryingChange,
}) => {
  // Local state (only for UI-specific state that doesn't need persistence)
  // Search state now comes from props for persistence
  const [error, setError] = useState<string>(''); // Error doesn't need persistence

  const handleSearch = async (): Promise<void> => {
    if (!question.trim() || isQuerying) return;
    
    try {
      onIsQueryingChange(true);
      setError('');
      onSearchResultsChange([]);
      onQaAnswerChange('');
      onQaSourcesChange([]);
      onLastSearchQueryChange(question);
      
      const queryType = activeTab === 'search' ? 'hybrid' : 'qa';
      const request: QueryRequest = {
        query: question,
        query_type: queryType,
        top_k: 10
      };
      
      const response = await axios.post<ApiResponse>('/api/search', request);
      
      if (response.data.success) {
        onHasSearchedChange(true);
        if (activeTab === 'search' && response.data.results) {
          onSearchResultsChange(response.data.results);
        } else if (activeTab === 'qa' && response.data.answer) {
          onQaAnswerChange(response.data.answer);
          onQaSourcesChange(response.data.sources || []);
        }
      } else {
        onHasSearchedChange(true);
        setError(response.data.error || 'Error executing query');
      }
    } catch (err) {
      console.error('Error querying:', err);
      const errorMessage = axios.isAxiosError(err)
        ? err.response?.data?.detail || err.response?.data?.error || 'Error executing query'
        : 'An unknown error occurred';
      setError(errorMessage);
      onHasSearchedChange(true);
    } finally {
      onIsQueryingChange(false);
    }
  };

  const handleTabChange = (_: any, newValue: string) => {
    onActiveTabChange(newValue);
    onSearchResultsChange([]);
    onQaAnswerChange('');
    onQaSourcesChange([]);
    setError('');
    onHasSearchedChange(false);
    onLastSearchQueryChange('');
  };

  return (
    <Box sx={{ p: 3 }}>
      <TabContext value={activeTab}>
        <Box sx={{ borderBottom: 1, borderColor: 'divider', mb: 2 }}>
          <Tabs value={activeTab} onChange={handleTabChange}>
            <Tab label="Hybrid Search" value="search" />
            <Tab label="AI Query" value="qa" />
          </Tabs>
        </Box>
        
        <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
          <TextField
            fullWidth
            label={activeTab === 'search' ? 'Search terms' : 'Ask a question'}
            variant="outlined"
            value={question}
            onChange={(e) => onQuestionChange(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
            size="small"
            placeholder={activeTab === 'search' 
              ? 'e.g., machine learning algorithms' 
              : 'e.g., What are the key findings?'
            }
            sx={{
              '& .MuiOutlinedInput-root': {
                backgroundColor: currentTheme.palette.background.paper,
                '& fieldset': {
                  borderColor: currentTheme.palette.divider,
                },
                '&:hover fieldset': {
                  borderColor: currentTheme.palette.primary.main,
                },
                '&.Mui-focused fieldset': {
                  borderColor: currentTheme.palette.primary.main,
                }
              }
            }}
          />
          <Button
            variant="contained"
            color="primary"
            onClick={handleSearch}
            disabled={isQuerying || !question.trim()}
            sx={{ minWidth: 150 }}
          >
            {isQuerying ? <CircularProgress size={24} /> : (activeTab === 'search' ? 'Search' : 'Ask')}
          </Button>
        </Box>
        
        <TabPanel value="search" sx={{ p: 0 }}>
          {searchResults.length > 0 && (
            <Box sx={{ mt: 2 }}>
              <Typography variant="h6" gutterBottom>
                Search Results ({searchResults.length})
              </Typography>
              {searchResults.map((result, index) => (
                <Paper key={index} sx={{ p: 2, mb: 2 }} elevation={1}>
                  <Typography variant="body2" color="text.secondary" gutterBottom>
                    <strong>Source:</strong>{' '}
                    {result.documents?.length ? (
                      <>
                        <SourceDocs docs={result.documents} />
                        {storeLabel(result.source) && ` | ${storeLabel(result.source)}`}
                      </>
                    ) : (result.file_name || result.metadata?.source || result.source || 'Unknown')} | 
                    <strong> Score:</strong> {result.score?.toFixed(3) || 'N/A'}
                  </Typography>
                  <Typography variant="body1">
                    {result.text || result.content || 'No content available'}
                  </Typography>
                </Paper>
              ))}
            </Box>
          )}
          {hasSearched && searchResults.length === 0 && !isQuerying && (
            <Paper sx={{ p: 3, mt: 2, textAlign: 'center' }} elevation={1}>
              <Typography variant="h6" color="text.secondary" gutterBottom>
                No results found
              </Typography>
              <Typography variant="body1" color="text.secondary">
                No results found for "{lastSearchQuery}". Try different search terms.
              </Typography>
            </Paper>
          )}
        </TabPanel>
        
        <TabPanel value="qa" sx={{ p: 0 }}>
          {qaAnswer && (
            <Paper sx={{ p: 2, mt: 2, bgcolor: 'background.paper' }} elevation={1}>
              <Typography variant="body1" component="div">
                <strong>Answer:</strong> {qaAnswer}
              </Typography>
              {qaSources.length > 0 && (
                <Typography variant="body2" color="text.secondary" component="div" sx={{ mt: 1.5 }}>
                  <SourceDocs docs={qaSources} label="Sources:" />
                </Typography>
              )}
            </Paper>
          )}
        </TabPanel>

        {error && (
          <Paper sx={{ p: 2, mt: 2, bgcolor: 'error.light' }} elevation={1}>
            <Typography variant="body1" color="error">
              <strong>Error:</strong> {error}
            </Typography>
          </Paper>
        )}
      </TabContext>
    </Box>
  );
};

// flexible-graphrag-ui/frontend-vue/src/components/SearchTab.vue
<template>
  <div class="pa-4">
    <v-tabs 
      v-model="activeTab" 
      class="mb-4"
      color="primary"
      slider-color="primary">
      <v-tab value="search">Hybrid Search</v-tab>
      <v-tab value="qa">AI Query</v-tab>
    </v-tabs>

    <!-- Search Input -->
    <div class="d-flex ga-2 mb-4">
      <v-text-field
        v-model="question"
        :label="activeTab === 'search' ? 'Search terms' : 'Ask a question'"
        variant="outlined"
        :placeholder="activeTab === 'search' 
          ? 'e.g., machine learning algorithms' 
          : 'e.g., What are the key findings?'"
        @keyup.enter="handleSearch"
        :disabled="isQuerying"
      ></v-text-field>
      <v-btn
        color="primary"
        size="large"
        :disabled="isQuerying || !question.trim()"
        :loading="isQuerying"
        @click="handleSearch"
        style="min-width: 150px;"
      >
        {{ activeTab === 'search' ? 'SEARCH' : 'ASK' }}
      </v-btn>
    </div>

    <v-window v-model="activeTab">
      <!-- Search Results Tab -->
      <v-window-item value="search">
        <div v-if="searchResults.length > 0" class="mt-4">
          <h3 class="mb-4">Search Results ({{ searchResults.length }})</h3>
          <v-card
            v-for="(result, index) in searchResults"
            :key="index"
            class="pa-4 mb-4"
            variant="outlined"
          >
            <div class="text-caption text-medium-emphasis mb-2">
              <strong>Source:</strong>
              <template v-if="result.documents?.length">
                <SourceDocs :docs="result.documents" /><template v-if="storeLabel(result.source)"> | {{ storeLabel(result.source) }}</template>
              </template>
              <template v-else>{{ result.file_name || result.metadata?.source || result.source || 'Unknown' }}</template> | 
              <strong> Score:</strong> {{ result.score?.toFixed(3) || 'N/A' }}
            </div>
            <p>{{ result.text || result.content || 'No content available' }}</p>
          </v-card>
        </div>
        
        <v-card
          v-if="hasSearched && searchResults.length === 0 && !isQuerying"
          class="pa-6 mt-4 text-center"
          variant="outlined"
        >
          <h3 class="text-medium-emphasis mb-2">No results found</h3>
          <p class="text-medium-emphasis">
            No results found for "{{ lastSearchQuery }}". Try different search terms.
          </p>
        </v-card>
      </v-window-item>

      <!-- Q&A Results Tab -->
      <v-window-item value="qa">
        <v-card
          v-if="qaAnswer"
          class="pa-4 mt-4"
          variant="outlined"
        >
          <div>
            <strong>Answer:</strong> {{ qaAnswer }}
          </div>
          <div v-if="qaSources.length" class="text-body-2 text-medium-emphasis mt-3">
            <SourceDocs :docs="qaSources" label="Sources:" />
          </div>
        </v-card>
      </v-window-item>
    </v-window>

    <!-- Error Message -->
    <v-alert
      v-if="error"
      type="error"
      class="mt-4"
      closable
      @click:close="error = ''"
    >
      {{ error }}
    </v-alert>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, watch } from 'vue';
import axios from 'axios';
import SourceDocs, { SourceDocument, storeLabel } from './SourceDocs.vue';

interface QueryRequest {
  query: string;
  query_type?: string;
  top_k?: number;
}

interface ApiResponse {
  success?: boolean;
  status?: string;
  message?: string;
  error?: string;
  answer?: string;
  sources?: SourceDocument[];
  results?: any[];
}

export default defineComponent({
  name: 'SearchTab',
  components: { SourceDocs },
  setup() {
    // State
    const activeTab = ref('search');
    const question = ref('');
    const searchResults = ref<any[]>([]);
    const qaAnswer = ref('');
    const qaSources = ref<SourceDocument[]>([]);
    const hasSearched = ref(false);
    const lastSearchQuery = ref('');
    const isQuerying = ref(false);
    const error = ref('');

    // Methods
    const handleSearch = async () => {
      if (!question.value.trim() || isQuerying.value) return;
      
      try {
        isQuerying.value = true;
        error.value = '';
        searchResults.value = [];
        qaAnswer.value = '';
        qaSources.value = [];
        lastSearchQuery.value = question.value;
        
        const queryType = activeTab.value === 'search' ? 'hybrid' : 'qa';
        const request: QueryRequest = {
          query: question.value,
          query_type: queryType,
          top_k: 10
        };
        
        const response = await axios.post<ApiResponse>('/api/search', request);
        
        if (response.data.success) {
          hasSearched.value = true;
          if (activeTab.value === 'search' && response.data.results) {
            searchResults.value = response.data.results;
          } else if (activeTab.value === 'qa' && response.data.answer) {
            qaAnswer.value = response.data.answer;
            qaSources.value = response.data.sources || [];
          }
        } else {
          hasSearched.value = true;
          error.value = response.data.error || 'Error executing query';
        }
      } catch (err) {
        console.error('Error querying:', err);
        const errorMessage = axios.isAxiosError(err)
          ? err.response?.data?.detail || err.response?.data?.error || 'Error executing query'
          : 'An unknown error occurred';
        error.value = errorMessage;
        hasSearched.value = true;
      } finally {
        isQuerying.value = false;
      }
    };

    // Clear results when tab changes
    watch(activeTab, () => {
      searchResults.value = [];
      qaAnswer.value = '';
      qaSources.value = [];
      error.value = '';
      hasSearched.value = false;
      lastSearchQuery.value = '';
    });

    return {
      activeTab,
      question,
      searchResults,
      qaAnswer,
      qaSources,
      storeLabel,
      hasSearched,
      lastSearchQuery,
      isQuerying,
      error,
      handleSearch,
    };
  },
});
</script>
