// flexible-graphrag-ui/frontend-react/src/components/SourcesTab.tsx
import React, { useState, useMemo, useCallback } from 'react';
import {
  Box,
  Typography,
  Button,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
} from '@mui/material';
import { Theme } from '@mui/material/styles';

interface SourcesTabProps {
  currentTheme: Theme;
  dataSource: string;
  selectedFiles: File[];
  folderPath: string;
  cmisUrl: string;
  cmisUsername: string;
  cmisPassword: string;
  alfrescoUrl: string;
  alfrescoUsername: string;
  alfrescoPassword: string;
  onDataSourceChange: (dataSource: string) => void;
  onSelectedFilesChange: (files: File[]) => void;
  onFolderPathChange: (folderPath: string) => void;
  onCmisUrlChange: (url: string) => void;
  onCmisUsernameChange: (username: string) => void;
  onCmisPasswordChange: (password: string) => void;
  onAlfrescoUrlChange: (url: string) => void;
  onAlfrescoUsernameChange: (username: string) => void;
  onAlfrescoPasswordChange: (password: string) => void;
  onConfigureProcessing: () => void;
  onSourcesConfigured: (data: {
    dataSource: string;
    files: File[];
    folderPath: string;
    cmisConfig?: any;
    alfrescoConfig?: any;
  }) => void;
}

export const SourcesTab: React.FC<SourcesTabProps> = ({ 
  currentTheme,
  dataSource,
  selectedFiles,
  folderPath,
  cmisUrl,
  cmisUsername,
  cmisPassword,
  alfrescoUrl,
  alfrescoUsername,
  alfrescoPassword,
  onDataSourceChange,
  onSelectedFilesChange,
  onFolderPathChange,
  onCmisUrlChange,
  onCmisUsernameChange,
  onCmisPasswordChange,
  onAlfrescoUrlChange,
  onAlfrescoUsernameChange,
  onAlfrescoPasswordChange,
  onConfigureProcessing, 
  onSourcesConfigured 
}) => {
  // Local state (only for UI-specific state that doesn't need persistence)
  const [isDragOver, setIsDragOver] = useState<boolean>(false);

  // Memoized placeholder values
  const cmisPlaceholder = useMemo(() => {
    const baseUrl = import.meta.env.VITE_CMIS_BASE_URL || 'http://localhost:8080';
    return `e.g., ${baseUrl}/alfresco/api/-default-/public/cmis/versions/1.1/atom`;
  }, []);

  const alfrescoPlaceholder = useMemo(() => {
    const baseUrl = import.meta.env.VITE_ALFRESCO_BASE_URL || 'http://localhost:8080';
    return `e.g., ${baseUrl}/alfresco`;
  }, []);

  // Form validation
  const isFormValid = useCallback((): boolean => {
    switch (dataSource) {
      case 'upload':
        return selectedFiles.length > 0;
      case 'cmis':
        return folderPath.trim() !== '' && 
               cmisUrl.trim() !== '' && 
               cmisUsername.trim() !== '' && 
               cmisPassword.trim() !== '';
      case 'alfresco':
        return folderPath.trim() !== '' && 
               alfrescoUrl.trim() !== '' && 
               alfrescoUsername.trim() !== '' && 
               alfrescoPassword.trim() !== '';
      default:
        return false;
    }
  }, [dataSource, selectedFiles.length, folderPath, cmisUrl, cmisUsername, cmisPassword, alfrescoUrl, alfrescoUsername, alfrescoPassword]);

  // File size formatting
  const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) {
      return bytes === 0 ? "0 B" : "1 KB";
    } else if (bytes < 1024 * 1024) {
      return `${Math.ceil(bytes / 1024)} KB`;
    } else {
      return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
    }
  };

  // File handling
  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (files) {
      // Use requestAnimationFrame to defer processing and improve perceived performance
      requestAnimationFrame(() => {
        const fileArray = Array.from(files);
        onSelectedFilesChange(fileArray);
        // Clear the input value only after successful processing to allow re-selecting same files
        event.target.value = '';
      });
    }
  };

  const handleFileDrop = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDragOver(false);
    
    const files = event.dataTransfer.files;
    if (files) {
      // Use requestAnimationFrame for consistency with file dialog
      requestAnimationFrame(() => {
        const fileArray = Array.from(files);
        onSelectedFilesChange(fileArray);
      });
    }
  };

  const handleDragOver = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'copy';
    }
  };

  const handleDragEnter = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDragOver(true);
    
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'copy';
    }
  };

  const handleDragLeave = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.stopPropagation();
    
    const rect = event.currentTarget.getBoundingClientRect();
    const x = event.clientX;
    const y = event.clientY;
    
    if (x < rect.left || x > rect.right || y < rect.top || y > rect.bottom) {
      setIsDragOver(false);
    }
  };

  const removeFile = (index: number) => {
    onSelectedFilesChange(selectedFiles.filter((_, i) => i !== index));
  };

  const handleConfigureProcessing = () => {
    const configData = {
      dataSource,
      files: selectedFiles,
      folderPath,
      cmisConfig: dataSource === 'cmis' ? {
        url: cmisUrl,
        username: cmisUsername,
        password: cmisPassword,
        folder_path: folderPath
      } : undefined,
      alfrescoConfig: dataSource === 'alfresco' ? {
        url: alfrescoUrl,
        username: alfrescoUsername,
        password: alfrescoPassword,
        path: folderPath
      } : undefined
    };
    
    onSourcesConfigured(configData);
    onConfigureProcessing();
  };

  const renderDataSourceFields = () => {
    switch (dataSource) {
      case 'upload':
        return (
          <Box sx={{ mb: 2 }}>
            <Box
              sx={{
                border: isDragOver ? '2px solid #ffffff' : '2px dashed #ffffff',
                borderRadius: 2,
                p: 3,
                textAlign: 'center',
                cursor: 'pointer',
                backgroundColor: isDragOver ? '#000000' : '#1976d2', // Black on hover, blue default like Vue
                transition: 'all 0.2s ease-in-out',
              }}
              onDrop={handleFileDrop}
              onDragOver={handleDragOver}
              onDragEnter={handleDragEnter}
              onDragLeave={handleDragLeave}
              onClick={() => document.getElementById('file-input')?.click()}
            >
              <Typography variant="h6" gutterBottom sx={{ color: '#ffffff' }}>
                Drop files here or click to select
              </Typography>
              <Typography variant="body2" sx={{ color: '#ffffff' }}>
                Supports: PDF, DOCX, XLSX, PPTX, TXT, MD, HTML, CSV, PNG, JPG
              </Typography>
              <input
                id="file-input"
                type="file"
                multiple
                accept=".pdf,.docx,.xlsx,.pptx,.txt,.md,.html,.csv,.png,.jpg,.jpeg"
                onChange={handleFileSelect}
                aria-label="Select files to upload"
                style={{ display: 'none' }}
              />
            </Box>
            
            {selectedFiles.length > 0 && (
              <Box sx={{ mt: 2 }}>
                <Typography variant="subtitle2" gutterBottom>
                  Selected Files ({selectedFiles.length}):
                </Typography>
                {selectedFiles.map((file, index) => (
                  <Box key={index} sx={{ 
                    display: 'flex', 
                    alignItems: 'center', 
                    justifyContent: 'space-between',
                    p: 1,
                    border: `1px solid ${currentTheme.palette.divider}`,
                    borderRadius: 1,
                    mb: 1
                  }}>
                    <Box>
                      <Typography variant="body2">{file.name}</Typography>
                      <Typography variant="caption" color="text.secondary">
                        {formatFileSize(file.size)}
                      </Typography>
                    </Box>
                    <Button
                      size="small"
                      color="error"
                      onClick={() => removeFile(index)}
                    >
                      Remove
                    </Button>
                  </Box>
                ))}
              </Box>
            )}
          </Box>
        );
      
      case 'cmis':
        return (
          <>
            <TextField
              fullWidth
              label="CMIS Repository URL"
              variant="outlined"
              value={cmisUrl}
              onChange={(e) => onCmisUrlChange(e.target.value)}
              size="small"
              sx={{ mb: 2 }}
              placeholder={cmisPlaceholder}
            />
            <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
              <TextField
                fullWidth
                label="Username"
                variant="outlined"
                value={cmisUsername}
                onChange={(e) => onCmisUsernameChange(e.target.value)}
                size="small"
              />
              <TextField
                fullWidth
                label="Password"
                type="password"
                variant="outlined"
                value={cmisPassword}
                onChange={(e) => onCmisPasswordChange(e.target.value)}
                size="small"
              />
            </Box>
            <TextField
              fullWidth
              label="Folder Path"
              variant="outlined"
              value={folderPath}
              onChange={(e) => onFolderPathChange(e.target.value)}
              size="small"
              sx={{ mb: 2 }}
              placeholder="e.g., /Sites/example/documentLibrary"
            />
          </>
        );
      
      case 'alfresco':
        return (
          <>
            <TextField
              fullWidth
              label="Alfresco Base URL"
              variant="outlined"
              value={alfrescoUrl}
              onChange={(e) => onAlfrescoUrlChange(e.target.value)}
              size="small"
              sx={{ mb: 2 }}
              placeholder={alfrescoPlaceholder}
            />
            <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
              <TextField
                fullWidth
                label="Username"
                variant="outlined"
                value={alfrescoUsername}
                onChange={(e) => onAlfrescoUsernameChange(e.target.value)}
                size="small"
              />
              <TextField
                fullWidth
                label="Password"
                type="password"
                variant="outlined"
                value={alfrescoPassword}
                onChange={(e) => onAlfrescoPasswordChange(e.target.value)}
                size="small"
              />
            </Box>
            <TextField
              fullWidth
              label="Path"
              variant="outlined"
              value={folderPath}
              onChange={(e) => onFolderPathChange(e.target.value)}
              size="small"
              sx={{ mb: 2 }}
              placeholder="e.g., /Sites/example/documentLibrary"
            />
          </>
        );
      
      default:
        return null;
    }
  };

  return (
    <Box sx={{ p: 3 }}>
      <Typography variant="h6" gutterBottom>
        Data Source Configuration
      </Typography>
      
      <FormControl fullWidth sx={{ mb: 2 }}>
        <InputLabel>Data Source</InputLabel>
        <Select
          value={dataSource}
          label="Data Source"
          onChange={(e) => onDataSourceChange(e.target.value)}
          size="small"
        >
          <MenuItem value="upload">File Upload</MenuItem>
          <MenuItem value="alfresco">Alfresco Repository</MenuItem>
          <MenuItem value="cmis">CMIS Repository</MenuItem>
        </Select>
      </FormControl>
      
      {renderDataSourceFields()}
      
      <Box sx={{ display: 'flex', gap: 1, alignItems: 'center', mt: 2 }}>
        <Button
          variant="contained"
          onClick={handleConfigureProcessing}
          disabled={!isFormValid()}
          sx={{ minWidth: 200 }}
        >
          Configure Processing →
        </Button>
      </Box>
    </Box>
  );
};

// flexible-graphrag-ui/frontend-vue/src/components/SourcesTab.vue
<template>
  <div class="pa-4">
    <h2 class="mb-4">Data Source Configuration</h2>
    
    <!-- Data Source Selection -->
    <v-select
      v-model="dataSource"
      :items="dataSourceOptions"
      label="Data Source"
      variant="outlined"
      class="mb-4"
    ></v-select>

    <!-- File Upload -->
    <template v-if="dataSource === 'upload'">
      <v-card
        :class="[
          'pa-6 mb-4 text-center cursor-pointer',
          isDragOver ? 'drag-over' : 'drag-normal'
        ]"
        :style="dropZoneStyle"
        @drop="handleFileDrop"
        @dragover="handleDragOver"
        @dragenter="handleDragEnter"
        @dragleave="handleDragLeave"
        @click="() => fileInputRef?.click()"
      >
        <h3 class="mb-2" :style="{ color: '#ffffff' }">
          Drop files here or click to select
        </h3>
        <p :style="{ color: '#ffffff' }">
          Supports: PDF, DOCX, XLSX, PPTX, TXT, MD, HTML, CSV, PNG, JPG
        </p>
        <input
          ref="fileInputRef"
          type="file"
          multiple
          accept=".pdf,.docx,.xlsx,.pptx,.txt,.md,.html,.csv,.png,.jpg,.jpeg"
          @change="handleFileSelect"
          style="display: none"
        />
      </v-card>

      <!-- Selected Files Display -->
      <div v-if="selectedFiles.length > 0" class="mb-4">
        <h4 class="mb-2">Selected Files ({{ selectedFiles.length }}):</h4>
        <v-card
          v-for="(file, index) in selectedFiles"
          :key="index"
          class="pa-3 mb-2"
          variant="outlined"
        >
          <div class="d-flex align-center justify-space-between">
            <div>
              <div class="font-weight-medium">{{ file.name }}</div>
              <div class="text-caption text-medium-emphasis">{{ formatFileSize(file.size) }}</div>
            </div>
            <v-btn
              color="error"
              variant="text"
              size="small"
              @click="removeFile(index)"
            >
              Remove
            </v-btn>
          </div>
        </v-card>
      </div>

      <!-- Upload Progress -->
      <div v-if="isUploading" class="mb-4">
        <p class="mb-2">Uploading files... {{ uploadProgress }}%</p>
        <v-progress-linear
          :model-value="uploadProgress"
          color="primary"
        ></v-progress-linear>
      </div>
    </template>

    <!-- CMIS Fields -->
    <template v-if="dataSource === 'cmis'">
      <v-text-field
        v-model="cmisUrl"
        label="CMIS Repository URL"
        variant="outlined"
        class="mb-4"
        :placeholder="cmisPlaceholder"
      ></v-text-field>
      <v-row class="mb-4">
        <v-col cols="6">
          <v-text-field
            v-model="cmisUsername"
            label="Username"
            variant="outlined"
          ></v-text-field>
        </v-col>
        <v-col cols="6">
          <v-text-field
            v-model="cmisPassword"
            label="Password"
            type="password"
            variant="outlined"
          ></v-text-field>
        </v-col>
      </v-row>
      <v-text-field
        v-model="folderPath"
        label="Folder Path"
        variant="outlined"
        class="mb-4"
        placeholder="e.g., /Sites/example/documentLibrary"
      ></v-text-field>
    </template>

    <!-- Alfresco Fields -->
    <template v-if="dataSource === 'alfresco'">
      <v-text-field
        v-model="alfrescoUrl"
        label="Alfresco Base URL"
        variant="outlined"
        class="mb-4"
        :placeholder="alfrescoPlaceholder"
      ></v-text-field>
      <v-row class="mb-4">
        <v-col cols="6">
          <v-text-field
            v-model="alfrescoUsername"
            label="Username"
            variant="outlined"
          ></v-text-field>
        </v-col>
        <v-col cols="6">
          <v-text-field
            v-model="alfrescoPassword"
            label="Password"
            type="password"
            variant="outlined"
          ></v-text-field>
        </v-col>
      </v-row>
      <v-text-field
        v-model="folderPath"
        label="Path"
        variant="outlined"
        class="mb-4"
        placeholder="e.g., /Sites/example/documentLibrary"
      ></v-text-field>
    </template>

    <!-- Configure Processing Button -->
    <div class="d-flex align-center mt-4">
      <v-btn
        color="primary"
        size="large"
        :disabled="!isFormValid"
        @click="configureProcessing"
      >
        CONFIGURE PROCESSING →
      </v-btn>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, watch } from 'vue';
import axios from 'axios';

export default defineComponent({
  name: 'SourcesTab',
  emits: ['configure-processing', 'sources-configured'],
  setup(_, { emit }) {
    // Data source options
    const dataSourceOptions = [
      { title: 'File Upload', value: 'upload' },
      { title: 'Alfresco Repository', value: 'alfresco' },
      { title: 'CMIS Repository', value: 'cmis' },
    ];

    // State
    const dataSource = ref('upload');
    const folderPath = ref('/Shared/GraphRAG');
    const selectedFiles = ref<File[]>([]);
    const isDragOver = ref(false);
    const fileInputRef = ref<HTMLInputElement>();
    const isUploading = ref(false);
    const uploadProgress = ref(0);

    // CMIS state
    const cmisUrl = ref(`${import.meta.env.VITE_CMIS_BASE_URL || 'http://localhost:8080'}/alfresco/api/-default-/public/cmis/versions/1.1/atom`);
    const cmisUsername = ref('admin');
    const cmisPassword = ref('admin');

    // Alfresco state
    const alfrescoUrl = ref(`${import.meta.env.VITE_ALFRESCO_BASE_URL || 'http://localhost:8080'}/alfresco`);
    const alfrescoUsername = ref('admin');
    const alfrescoPassword = ref('admin');

    // Computed
    const cmisPlaceholder = computed(() => {
      const baseUrl = import.meta.env.VITE_CMIS_BASE_URL || 'http://localhost:8080';
      return `e.g., ${baseUrl}/alfresco/api/-default-/public/cmis/versions/1.1/atom`;
    });

    const alfrescoPlaceholder = computed(() => {
      const baseUrl = import.meta.env.VITE_ALFRESCO_BASE_URL || 'http://localhost:8080';
      return `e.g., ${baseUrl}/alfresco`;
    });

    const dropZoneStyle = computed(() => ({
      border: isDragOver.value ? '2px solid #ffffff' : '2px dashed #ffffff',
      backgroundColor: isDragOver.value ? '#000000' : '#1976d2', // Black on hover, blue default like React
      transition: 'all 0.2s ease-in-out',
    }));

    const isFormValid = computed(() => {
      switch (dataSource.value) {
        case 'upload':
          return selectedFiles.value.length > 0;
        case 'cmis':
          return folderPath.value.trim() !== '' && 
                 cmisUrl.value.trim() !== '' && 
                 cmisUsername.value.trim() !== '' && 
                 cmisPassword.value.trim() !== '';
        case 'alfresco':
          return folderPath.value.trim() !== '' && 
                 alfrescoUrl.value.trim() !== '' && 
                 alfrescoUsername.value.trim() !== '' && 
                 alfrescoPassword.value.trim() !== '';
        default:
          return false;
      }
    });

    // Methods
    const formatFileSize = (bytes: number): string => {
      if (bytes < 1024) {
        return bytes === 0 ? "0 B" : "1 KB";
      } else if (bytes < 1024 * 1024) {
        return `${Math.ceil(bytes / 1024)} KB`;
      } else {
        return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
      }
    };

    const handleFileSelect = (event: Event) => {
      const target = event.target as HTMLInputElement;
      const files = target.files;
      if (files) {
        // Use requestAnimationFrame to defer processing and improve perceived performance
        requestAnimationFrame(() => {
          selectedFiles.value = Array.from(files);
          // Clear the input value only after successful processing to allow re-selecting same files
          target.value = '';
        });
      }
    };

    const handleFileDrop = (event: DragEvent) => {
      event.preventDefault();
      event.stopPropagation();
      isDragOver.value = false;
      
      const files = event.dataTransfer?.files;
      if (files) {
        // Use requestAnimationFrame for consistency with file dialog
        requestAnimationFrame(() => {
          selectedFiles.value = Array.from(files);
        });
      }
    };

    const handleDragOver = (event: DragEvent) => {
      event.preventDefault();
      event.stopPropagation();
      if (event.dataTransfer) {
        event.dataTransfer.dropEffect = 'copy';
      }
    };

    const handleDragEnter = (event: DragEvent) => {
      event.preventDefault();
      event.stopPropagation();
      isDragOver.value = true;
      if (event.dataTransfer) {
        event.dataTransfer.dropEffect = 'copy';
      }
    };

    const handleDragLeave = (event: DragEvent) => {
      event.preventDefault();
      event.stopPropagation();
      
      const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
      const x = event.clientX;
      const y = event.clientY;
      
      if (x < rect.left || x > rect.right || y < rect.top || y > rect.bottom) {
        isDragOver.value = false;
      }
    };

    const removeFile = (index: number) => {
      selectedFiles.value = selectedFiles.value.filter((_, i) => i !== index);
    };

    const configureProcessing = () => {
      emit('sources-configured', {
        dataSource: dataSource.value,
        files: selectedFiles.value,
        folderPath: folderPath.value,
        cmisConfig: dataSource.value === 'cmis' ? {
          url: cmisUrl.value,
          username: cmisUsername.value,
          password: cmisPassword.value,
          folder_path: folderPath.value
        } : undefined,
        alfrescoConfig: dataSource.value === 'alfresco' ? {
          url: alfrescoUrl.value,
          username: alfrescoUsername.value,
          password: alfrescoPassword.value,
          path: folderPath.value
        } : undefined,
      });
      emit('configure-processing');
    };

    // Clear selected files when data source changes
    watch(dataSource, () => {
      selectedFiles.value = [];
      // Note: Preserve form field values (URLs, credentials, etc.) so users don't have to retype
    });

    return {
      dataSourceOptions,
      dataSource,
      folderPath,
      selectedFiles,
      isDragOver,
      fileInputRef,
      isUploading,
      uploadProgress,
      cmisUrl,
      cmisUsername,
      cmisPassword,
      alfrescoUrl,
      alfrescoUsername,
      alfrescoPassword,
      cmisPlaceholder,
      alfrescoPlaceholder,
      dropZoneStyle,
      isFormValid,
      formatFileSize,
      handleFileSelect,
      handleFileDrop,
      handleDragOver,
      handleDragEnter,
      handleDragLeave,
      removeFile,
      configureProcessing,
    };
  },
});
</script>

<style scoped>
.cursor-pointer {
  cursor: pointer;
}

/* CSS hover styles removed - now handled by computed dropZoneStyle */

.drag-normal {
  background-color: #1976d2 !important;
}
</style>
