// flexible-graphrag-ui/frontend-vue/src/components/SourceDocs.vue
<template>
  <span v-if="docs && docs.length">
    <strong v-if="label" class="mr-1">{{ label }}</strong>
    <template v-for="(doc, i) in docs" :key="doc.doc_id || doc.name || i">
      <a
        v-if="doc.open_url"
        :href="doc.open_url"
        target="_blank"
        rel="noopener noreferrer"
        class="source-doc-link"
        :title="doc.path || doc.name"
      >{{ doc.name }}</a>
      <span v-else :title="doc.path || doc.name">{{ doc.name }}</span>
      <span v-if="i < docs.length - 1">, </span>
    </template>
  </span>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

/** A document a search result or an answer came from (backend doc_refs.py). */
export interface SourceDocument {
  doc_id: string;
  name: string;
  path: string;
  source_type: string;  // 'alfresco' | 'nuxeo' | '' (other sources)
  node_id: string;      // repository node id (Alfresco / Nuxeo)
  parent_id?: string;   // an Alfresco document's folder id ('' when unknown)
  open_url: string;     // link to the document (Alfresco Share, Nuxeo Web UI); '' when none
}

/** The store part of a result's source label ("a.txt | Neo4j property graph" -> "Neo4j property graph"). */
export const storeLabel = (source?: string): string => {
  const s = source || '';
  const i = s.lastIndexOf(' | ');
  return i >= 0 ? s.slice(i + 3) : '';
};

/**
 * The documents a search result or an answer came from. A document with an open link
 * (Alfresco Share, Nuxeo Web UI) opens in a new tab; others are plain names.
 */
export default defineComponent({
  name: 'SourceDocs',
  props: {
    docs: { type: Array as PropType<SourceDocument[]>, default: () => [] },
    /** Text before the list, e.g. "Sources:". */
    label: { type: String, default: '' },
  },
});
</script>

<style scoped>
.source-doc-link {
  color: rgb(var(--v-theme-primary));
  text-decoration: none;
}
.source-doc-link:hover {
  text-decoration: underline;
}
</style>

// flexible-graphrag-ui/frontend-angular/projects/flexible-graphrag-angular-lib/src/lib/components/source-docs/source-docs.ts
import { Component, Input } from '@angular/core';
import { FlexibleGraphragConfigService } from '../../config.service';
import { SourceDocument } from '../../models/api.models';

/**
 * The documents a search result or an answer came from, each one a link when it can be opened:
 * the host's own viewer first (`openDocument`, e.g. ACA for Alfresco nodes), otherwise the
 * backend's `open_url` (Alfresco Share, Nuxeo Web UI) in a new tab, otherwise plain text.
 */
@Component({
  selector: 'app-source-docs',
  template: `
    <span class="source-docs" *ngIf="docs?.length">
      <span *ngIf="label" class="source-docs-label">{{ label }}</span>
      <ng-container *ngFor="let doc of docs; let last = last">
        <a *ngIf="canOpen(doc); else plain" href="" class="source-doc-link" (click)="open($event, doc)"
           [title]="doc.path || doc.name">{{ doc.name }}</a>
        <ng-template #plain><span class="source-doc" [title]="doc.path || doc.name">{{ doc.name }}</span></ng-template>
        <span *ngIf="!last">, </span>
      </ng-container>
    </span>
  `,
  styles: [`
    .source-docs-label { font-weight: 600; margin-right: 4px; }
    .source-doc-link { color: #1976d2; text-decoration: none; cursor: pointer; }
    .source-doc-link:hover { text-decoration: underline; }
    :host-context(.dark-theme) .source-doc-link { color: #90caf9; }
  `],
  standalone: false
})
export class SourceDocsComponent {
  @Input() docs: SourceDocument[] | null | undefined = [];
  /** Text before the list, e.g. "Sources:". */
  @Input() label = '';

  constructor(private fgConfig: FlexibleGraphragConfigService) {}

  canOpen(doc: SourceDocument): boolean {
    return this.fgConfig.canOpenDocument(doc) || !!doc.open_url;
  }

  open(event: Event, doc: SourceDocument): void {
    event.preventDefault();
    if (this.fgConfig.openDocument(doc)) return;
    if (doc.open_url) window.open(doc.open_url, '_blank', 'noopener');
  }
}
