// flexible-graphrag-ui/frontend-react/src/components/sources/AzureBlobSourceForm.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { TextField } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface AzureBlobSourceFormProps extends BaseSourceFormProps {
  connectionString: string;
  containerName: string;
  blobName: string;
  accountName: string;
  accountKey: string;
  onConnectionStringChange: (connectionString: string) => void;
  onContainerNameChange: (containerName: string) => void;
  onBlobNameChange: (blobName: string) => void;
  onAccountNameChange: (accountName: string) => void;
  onAccountKeyChange: (accountKey: string) => void;
}

export const AzureBlobSourceForm: React.FC<AzureBlobSourceFormProps> = ({
  currentTheme,
  connectionString,
  containerName,
  blobName,
  accountName,
  accountKey,
  onConnectionStringChange,
  onContainerNameChange,
  onBlobNameChange,
  onAccountNameChange,
  onAccountKeyChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const [prefix, setPrefix] = useState('');
  const [accountUrl, setAccountUrl] = useState('');

  const isValid = useMemo(() => {
    // Method 1 requires: account_url, container_name, account_name, account_key
    return accountUrl.trim() !== '' && 
           containerName.trim() !== '' && 
           accountName.trim() !== '' && 
           accountKey.trim() !== '';
  }, [accountUrl, containerName, accountName, accountKey]);

  const config = useMemo(() => ({
    // Method 1 (Account Key Authentication) fields
    container_name: containerName,
    account_url: accountUrl,
    blob: blobName || undefined,
    prefix: prefix || undefined,
    account_name: accountName,
    account_key: accountKey
  }), [containerName, accountUrl, blobName, prefix, accountName, accountKey]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  return (
    <BaseSourceForm
      title="Azure Blob Storage"
      description="Connect to Azure Blob Storage using Account Key Authentication (Method 1)"
    >
      <TextField
        fullWidth
        label="Account URL *"
        variant="outlined"
        value={accountUrl}
        onChange={(e) => setAccountUrl(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="https://mystorageaccount.blob.core.windows.net"
        helperText="Azure Storage account URL (required)"
        required
      />
      <TextField
        fullWidth
        label="Container Name *"
        variant="outlined"
        value={containerName}
        onChange={(e) => onContainerNameChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="my-container"
        required
      />
      <TextField
        fullWidth
        label="Blob (Optional)"
        variant="outlined"
        value={blobName}
        onChange={(e) => onBlobNameChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="specific-file.pdf"
        helperText="Optional: specific blob/file name"
      />
      <TextField
        fullWidth
        label="Prefix (Optional)"
        variant="outlined"
        value={prefix}
        onChange={(e) => setPrefix(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="documents/reports/"
        helperText="Optional: folder path prefix within container"
      />
      <TextField
        fullWidth
        label="Account Name *"
        variant="outlined"
        value={accountName}
        onChange={(e) => onAccountNameChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="mystorageaccount"
        helperText="Azure Storage account name (required)"
        required
      />
      <TextField
        fullWidth
        label="Account Key *"
        variant="outlined"
        value={accountKey}
        onChange={(e) => onAccountKeyChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        type="password"
        placeholder="account-key-here"
        helperText="Azure Storage account key (required)"
        required
      />
    </BaseSourceForm>
  );
};

// flexible-graphrag-ui/frontend-angular/src/app/components/sources/azure-blob-source-form.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';

export interface AzureBlobSourceConfig {
  container_name: string;
  account_url: string;
  blob?: string;
  prefix?: string;
  account_name: string;
  account_key: string;
}

@Component({
  selector: 'app-azure-blob-source-form',
  template: `
    <app-base-source-form 
      title="Azure Blob Storage" 
      description="Connect to Azure Blob Storage using Account Key Authentication (Method 1)">
      
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Account URL *</mat-label>
        <input matInput
               [(ngModel)]="accountUrl"
               (ngModelChange)="onAccountUrlChange()"
               placeholder="https://mystorageaccount.blob.core.windows.net"
               required />
        <mat-hint>Azure Storage account URL (required)</mat-hint>
      </mat-form-field>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Container Name *</mat-label>
        <input matInput
               [(ngModel)]="containerName"
               (ngModelChange)="onContainerNameChange()"
               placeholder="my-container"
               required />
      </mat-form-field>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Blob (Optional)</mat-label>
        <input matInput
               [(ngModel)]="blobName"
               (ngModelChange)="onBlobNameChange()"
               placeholder="specific-file.pdf" />
        <mat-hint>Optional: specific blob/file name</mat-hint>
      </mat-form-field>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Prefix (Optional)</mat-label>
        <input matInput
               [(ngModel)]="prefix"
               (ngModelChange)="onPrefixChange()"
               placeholder="documents/reports/" />
        <mat-hint>Optional: folder path prefix within container</mat-hint>
      </mat-form-field>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Account Name *</mat-label>
        <input matInput
               [(ngModel)]="accountName"
               (ngModelChange)="onAccountNameChange()"
               placeholder="mystorageaccount"
               required />
        <mat-hint>Azure Storage account name (required)</mat-hint>
      </mat-form-field>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Account Key *</mat-label>
        <input matInput
               type="password"
               [(ngModel)]="accountKey"
               (ngModelChange)="onAccountKeyChange()"
               placeholder="account-key-here"
               required />
        <mat-hint>Azure Storage account key (required)</mat-hint>
      </mat-form-field>
    </app-base-source-form>
  `,
  styles: [`
    .full-width {
      width: 100%;
      margin-bottom: 16px;
    }
  `],
  standalone: false
})
export class AzureBlobSourceFormComponent implements OnInit, OnDestroy {
  @Input() connectionString: string = '';
  @Input() containerName: string = '';
  @Input() blobName: string = '';
  @Input() accountName: string = '';
  @Input() accountKey: string = '';
  
  @Output() connectionStringChange = new EventEmitter<string>();
  @Output() containerNameChange = new EventEmitter<string>();
  @Output() blobNameChange = new EventEmitter<string>();
  @Output() accountNameChange = new EventEmitter<string>();
  @Output() accountKeyChange = new EventEmitter<string>();
  @Output() configurationChange = new EventEmitter<AzureBlobSourceConfig>();
  @Output() validationChange = new EventEmitter<boolean>();

  prefix: string = '';
  accountUrl: string = '';

  ngOnInit() {
    this.updateValidationAndConfig();
  }

  ngOnDestroy() {
    // Cleanup if needed
  }

  private updateValidationAndConfig() {
    // Method 1 requires: account_url, container_name, account_name, account_key
    const isValid = this.accountUrl.trim() !== '' && 
                   this.containerName.trim() !== '' && 
                   this.accountName.trim() !== '' && 
                   this.accountKey.trim() !== '';
    
    const config: AzureBlobSourceConfig = {
      // Method 1 (Account Key Authentication) fields
      container_name: this.containerName,
      account_url: this.accountUrl,
      blob: this.blobName || undefined,
      prefix: this.prefix || undefined,
      account_name: this.accountName,
      account_key: this.accountKey
    };
    
    this.validationChange.emit(isValid);
    this.configurationChange.emit(config);
  }

  onAccountUrlChange(): void {
    this.updateValidationAndConfig();
  }

  onContainerNameChange(): void {
    this.containerNameChange.emit(this.containerName);
    this.updateValidationAndConfig();
  }

  onBlobNameChange(): void {
    this.blobNameChange.emit(this.blobName);
    this.updateValidationAndConfig();
  }

  onPrefixChange(): void {
    this.updateValidationAndConfig();
  }

  onAccountNameChange(): void {
    this.accountNameChange.emit(this.accountName);
    this.updateValidationAndConfig();
  }

  onAccountKeyChange(): void {
    this.accountKeyChange.emit(this.accountKey);
    this.updateValidationAndConfig();
  }
}
