// flexible-graphrag-ui/frontend-vue/src/components/ChatTab.vue
<template>
  <div class="pa-4 d-flex flex-column chat-view-container">
    <!-- Removed header to save space - Clear History button moved to input area -->

    <!-- Chat Messages -->
    <v-card
      ref="chatContainer"
      class="flex-grow-1 pa-4 mb-4 overflow-y-auto chat-messages-card"
    >
      <!-- Welcome Message -->
      <div
        v-if="chatMessages.length === 0"
        class="d-flex flex-column align-center justify-center h-100 text-medium-emphasis"
      >
        <v-avatar size="48" class="mb-4" color="grey-lighten-3">
          <img :src="agentIcon" alt="Assistant" style="width: 32px; height: 32px; border-radius: 50%;" />
        </v-avatar>
        <h3 class="mb-2">Welcome to Flexible GraphRAG Chat</h3>
        <p class="text-center">
          Ask questions about your documents and get conversational answers.
          <br />
          The AI will provide detailed responses based on your processed documents.
        </p>
      </div>

      <!-- Chat Messages List -->
      <div v-else>
        <div
          v-for="(message, index) in chatMessages"
          :key="message.id"
          class="mb-4"
        >
          <div
            :class="[
              'd-flex align-start',
              message.type === 'user' ? 'flex-row-reverse' : 'flex-row'
            ]"
          >
            <!-- Avatar -->
            <v-avatar
              :color="message.type === 'user' ? 'primary' : 'success'"
              size="32"
              class="mx-2"
            >
              <v-icon v-if="message.type === 'user'" color="white">mdi-account</v-icon>
              <img v-else :src="agentIcon" alt="Assistant" style="width: 24px; height: 24px; border-radius: 50%;" />
            </v-avatar>

            <!-- Message Content -->
            <v-card
              :class="[
                'pa-3',
                message.type === 'user' ? 'bg-blue-lighten-5' : 'bg-white'
              ]"
              :style="{ 
                maxWidth: message.type === 'user' ? '70%' : '80%',
                color: '#000000'
              }"
            >
              <!-- Loading State -->
              <div v-if="message.isLoading" class="d-flex align-center ga-2">
                <v-progress-circular
                  indeterminate
                  size="16"
                  width="2"
                  color="primary"
                ></v-progress-circular>
                <span class="text-caption text-medium-emphasis">Thinking...</span>
              </div>

              <!-- Message Content -->
              <div v-else>
                <p class="mb-2">{{ message.content }}</p>
                <div v-if="message.sources?.length" class="text-caption mb-2">
                  <SourceDocs :docs="message.sources" label="Sources:" />
                </div>
                <div class="text-caption" style="color: #333333; font-weight: 500;">
                  {{ formatTime(message.timestamp) }}
                </div>
              </div>
            </v-card>
          </div>
        </div>
      </div>
    </v-card>

    <!-- Input Area -->
    <div class="d-flex align-center ga-2">
      <v-textarea
        v-model="chatInput"
        placeholder="Ask a question and press Enter or click arrow, Shift+Enter for a new line"
        variant="filled"
        rows="1"
        auto-grow
        max-rows="3"
        :disabled="isQuerying"
        @keydown.enter.exact.prevent="handleChatSubmit"
        @keydown.enter.shift.exact="() => {}"
        class="flex-grow-1"
      ></v-textarea>
      
      <v-btn
        icon
        color="primary"
        size="large"
        :disabled="!chatInput.trim() || isQuerying"
        :loading="isQuerying"
        @click="handleChatSubmit"
        style="width: 48px; height: 48px;"
      >
        <v-icon>mdi-send</v-icon>
      </v-btn>

      <v-btn
        variant="outlined"
        size="small"
        :disabled="chatMessages.length === 0"
        @click="clearChatHistory"
        class="ml-2"
      >
        CLEAR HISTORY
      </v-btn>
    </div>

    <!-- Error Message -->
    <v-alert
      v-if="error"
      type="error"
      class="mt-4"
      closable
      @click:close="error = ''"
    >
      {{ error }}
    </v-alert>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, nextTick, watch } from 'vue';
import axios from 'axios';
import agentIcon from '../assets/agent.png';
import SourceDocs, { SourceDocument } from './SourceDocs.vue';

interface ChatMessage {
  id: string;
  type: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  queryType?: 'search' | 'qa';
  results?: any[];
  sources?: SourceDocument[];
  isLoading?: boolean;
}

interface QueryRequest {
  query: string;
  query_type?: string;
  top_k?: number;
}

interface ApiResponse {
  success?: boolean;
  status?: string;
  message?: string;
  error?: string;
  answer?: string;
  sources?: SourceDocument[];
  results?: any[];
}

export default defineComponent({
  name: 'ChatTab',
  components: { SourceDocs },
  setup() {
    // State
    const chatMessages = ref<ChatMessage[]>([]);
    const chatInput = ref('');
    const isQuerying = ref(false);
    const error = ref('');
    const chatContainer = ref<HTMLElement>();

    // Methods
    const formatTime = (timestamp: Date): string => {
      return timestamp.toLocaleTimeString();
    };

    const scrollToBottom = async () => {
      await nextTick();
      if (chatContainer.value) {
        // Get the actual DOM element from the v-card component
        const domElement = chatContainer.value.$el || chatContainer.value;
        if (domElement) {
          domElement.scrollTop = domElement.scrollHeight;
        }
      }
    };

    const handleChatSubmit = async () => {
      if (!chatInput.value.trim() || isQuerying.value) return;
      
      const userMessage: ChatMessage = {
        id: Date.now().toString(),
        type: 'user',
        content: chatInput.value.trim(),
        timestamp: new Date(),
        queryType: 'qa'
      };
      
      // Add user message
      chatMessages.value.push(userMessage);
      
      // Add loading assistant message
      const loadingMessage: ChatMessage = {
        id: (Date.now() + 1).toString(),
        type: 'assistant',
        content: '',
        timestamp: new Date(),
        queryType: 'qa',
        isLoading: true
      };
      chatMessages.value.push(loadingMessage);
      
      const currentInput = chatInput.value;
      chatInput.value = '';
      
      try {
        isQuerying.value = true;
        error.value = '';
        
        const request: QueryRequest = {
          query: currentInput,
          query_type: 'qa',
          top_k: 10
        };
        
        const response = await axios.post<ApiResponse>('/api/search', request);
        
        // Remove loading message
        const messageIndex = chatMessages.value.findIndex(msg => msg.id === loadingMessage.id);
        if (messageIndex !== -1) {
          chatMessages.value.splice(messageIndex, 1);
        }
        
        if (response.data.success) {
          const assistantMessage: ChatMessage = {
            id: (Date.now() + 2).toString(),
            type: 'assistant',
            content: response.data.answer || 'No answer provided',
            sources: response.data.sources || [],
            timestamp: new Date(),
            queryType: 'qa'
          };
          chatMessages.value.push(assistantMessage);
        } else {
          const errorMessage: ChatMessage = {
            id: (Date.now() + 2).toString(),
            type: 'assistant',
            content: `Error: ${response.data.error || 'Unknown error occurred'}`,
            timestamp: new Date(),
            queryType: 'qa'
          };
          chatMessages.value.push(errorMessage);
        }
      } catch (err) {
        console.error('Error in chat query:', err);
        const errorMessage = axios.isAxiosError(err)
          ? err.response?.data?.detail || err.response?.data?.error || 'Error executing query'
          : 'An unknown error occurred';
        
        // Remove loading message
        const messageIndex = chatMessages.value.findIndex(msg => msg.id === loadingMessage.id);
        if (messageIndex !== -1) {
          chatMessages.value.splice(messageIndex, 1);
        }
        
        const errorMsg: ChatMessage = {
          id: (Date.now() + 2).toString(),
          type: 'assistant',
          content: `Error: ${errorMessage}`,
          timestamp: new Date(),
          queryType: 'qa'
        };
        chatMessages.value.push(errorMsg);
      } finally {
        isQuerying.value = false;
      }
    };

    const clearChatHistory = () => {
      chatMessages.value = [];
    };

    // Auto-scroll when messages change (like React's useEffect)
    watch(chatMessages, () => {
      nextTick(() => {
        if (chatContainer.value) {
          // Get the actual DOM element from the v-card component
          const domElement = chatContainer.value.$el || chatContainer.value;
          if (domElement) {
            domElement.scrollTop = domElement.scrollHeight;
          }
        }
      });
    }, { deep: true });

    return {
      chatMessages,
      chatInput,
      isQuerying,
      error,
      chatContainer,
      agentIcon,
      formatTime,
      handleChatSubmit,
      clearChatHistory,
    };
  },
});
</script>

<style scoped>
.h-100 {
  height: 100%;
}

.overflow-y-auto {
  overflow-y: auto;
}

.flex-grow-1 {
  flex-grow: 1;
}

.chat-view-container {
  height: calc(100vh - 220px); /* Increased offset to prevent outer scrollbars */
}

.chat-messages-card {
  background-color: #f8f9fa !important; /* Light gray background for light mode */
  flex: 1; /* Take remaining space after header and input */
  min-height: 200px !important; /* Reduced minimum height to prevent empty scrollbars */
}

/* Dark theme styling */
.v-theme--dark .chat-messages-card {
  background-color: #2d2d2d !important; /* Dark background for dark mode */
  flex: 1; /* Take remaining space after header and input */
  min-height: 200px !important; /* Reduced minimum height to prevent empty scrollbars */
}
</style>

// flexible-graphrag-ui/frontend-react/src/components/ChatTab.tsx
import React, { useEffect, useRef } from 'react';
import {
  Box,
  Typography,
  Button,
  TextField,
  Paper,
  CircularProgress,
  List,
  ListItem,
  Avatar,
  Divider,
  IconButton,
} from '@mui/material';
import SendIcon from '@mui/icons-material/Send';
import PersonIcon from '@mui/icons-material/Person';
import { Theme } from '@mui/material/styles';
import axios from 'axios';
import { QueryRequest, ApiResponse, ChatMessage } from '../types/api';
import agentIcon from '../agent.png';
import { SourceDocs } from './SourceDocs';

interface ChatTabProps {
  currentTheme: Theme;
  isDarkMode: boolean;
  chatMessages: ChatMessage[];
  chatInput: string;
  isQuerying: boolean;
  onChatMessagesChange: (messages: ChatMessage[]) => void;
  onChatInputChange: (input: string) => void;
  onIsQueryingChange: (isQuerying: boolean) => void;
}

export const ChatTab: React.FC<ChatTabProps> = ({ 
  currentTheme, 
  isDarkMode,
  chatMessages,
  chatInput,
  isQuerying,
  onChatMessagesChange,
  onChatInputChange,
  onIsQueryingChange,
}) => {
  // Local state (only for UI-specific state that doesn't need persistence)  
  const chatContainerRef = useRef<HTMLDivElement>(null);
  // Chat state now comes from props for persistence

  // Auto-scroll to bottom of chat
  const scrollToBottom = () => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
  };

  // Auto-scroll when messages change
  useEffect(() => {
    scrollToBottom();
  }, [chatMessages]);

  // Chat functionality
  const handleChatSubmit = async (): Promise<void> => {
    if (!chatInput.trim() || isQuerying) return;
    
    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      type: 'user',
      content: chatInput.trim(),
      timestamp: new Date(),
      queryType: 'qa'
    };
    
    // Add user message
    onChatMessagesChange([...chatMessages, userMessage]);
    
    // Add loading assistant message
    const loadingMessage: ChatMessage = {
      id: (Date.now() + 1).toString(),
      type: 'assistant',
      content: '',
      timestamp: new Date(),
      queryType: 'qa',
      isLoading: true
    };
    onChatMessagesChange([...chatMessages, userMessage, loadingMessage]);
    
    const currentInput = chatInput;
    onChatInputChange('');
    
    try {
      onIsQueryingChange(true);
      
      const request: QueryRequest = {
        query: currentInput,
        query_type: 'qa',
        top_k: 10
      };
      
      const response = await axios.post<ApiResponse>('/api/search', request);
      
      // Remove loading message and add response
      const messagesWithoutLoading = [...chatMessages, userMessage].filter(msg => msg.id !== loadingMessage.id);
      
      if (response.data.success) {
        const assistantMessage: ChatMessage = {
          id: (Date.now() + 2).toString(),
          type: 'assistant',
          content: response.data.answer || 'No answer provided',
          sources: response.data.sources || [],
          timestamp: new Date(),
          queryType: 'qa'
        };
        onChatMessagesChange([...messagesWithoutLoading, assistantMessage]);
      } else {
        const errorMessage: ChatMessage = {
          id: (Date.now() + 2).toString(),
          type: 'assistant',
          content: `Error: ${response.data.error || 'Unknown error occurred'}`,
          timestamp: new Date(),
          queryType: 'qa'
        };
        onChatMessagesChange([...messagesWithoutLoading, errorMessage]);
      }
    } catch (err) {
      console.error('Error in chat query:', err);
      const errorMessage = axios.isAxiosError(err)
        ? err.response?.data?.detail || err.response?.data?.error || 'Error executing query'
        : 'An unknown error occurred';
      
      // Remove loading message and add error
      const messagesWithoutLoading = [...chatMessages, userMessage].filter(msg => msg.id !== loadingMessage.id);
      const errorMsg: ChatMessage = {
        id: (Date.now() + 2).toString(),
        type: 'assistant',
        content: `Error: ${errorMessage}`,
        timestamp: new Date(),
        queryType: 'qa'
      };
      onChatMessagesChange([...messagesWithoutLoading, errorMsg]);
    } finally {
      onIsQueryingChange(false);
    }
  };

  const clearChatHistory = () => {
    onChatMessagesChange([]);
  };

  return (
    <Box sx={{ 
      p: 3, 
      height: 'calc(100vh - 230px)', // Increased offset to prevent QHD scrollbars
      display: 'flex', 
      flexDirection: 'column', 
      overflow: 'hidden' 
    }}>
      {/* Removed header to save space - Clear History button moved to input area */}

      {/* Chat Messages */}
      <Paper 
        ref={chatContainerRef}
        sx={{ 
          flex: 1, // Take remaining space after header and input
          p: 2, 
          mb: 2, 
          overflowY: 'auto',
          bgcolor: isDarkMode ? '#2d2d2d' : '#f8f9fa',
          minHeight: '200px' // Reduced minimum height to prevent empty scrollbars
        }}
      >
        {chatMessages.length === 0 ? (
          <Box sx={{ 
            display: 'flex', 
            flexDirection: 'column', 
            alignItems: 'center', 
            justifyContent: 'center', 
            height: '100%',
            color: currentTheme.palette.text.secondary
          }}>
            <img 
              src={agentIcon} 
              alt="Assistant" 
              style={{ 
                width: 48, 
                height: 48, 
                opacity: 0.5, 
                marginBottom: 16,
                backgroundColor: 'transparent',
                borderRadius: '50%'
              }} 
            />
            <Typography variant="h6" gutterBottom sx={{ color: currentTheme.palette.text.primary, fontWeight: 600 }}>
              Welcome to Flexible GraphRAG Chat
            </Typography>
            <Typography variant="body2" textAlign="center" sx={{ color: currentTheme.palette.text.secondary }}>
              Ask questions about your documents and get conversational answers.
              <br />
              The AI will provide detailed responses based on your processed documents.
            </Typography>
          </Box>
        ) : (
          <List sx={{ p: 0 }}>
            {chatMessages.map((message, index) => (
              <React.Fragment key={message.id}>
                <ListItem 
                  sx={{ 
                    display: 'flex', 
                    flexDirection: message.type === 'user' ? 'row-reverse' : 'row',
                    alignItems: 'flex-start',
                    px: 1,
                    py: 1
                  }}
                >
                  <Avatar 
                    sx={{ 
                      bgcolor: message.type === 'user' ? currentTheme.palette.primary.main : currentTheme.palette.success.main,
                      mx: 1,
                      width: 32,
                      height: 32
                    }}
                  >
                    {message.type === 'user' ? (
                      <PersonIcon />
                    ) : (
                      <img 
                        src={agentIcon} 
                        alt="Assistant" 
                        style={{ 
                          width: 28, 
                          height: 28, 
                          backgroundColor: 'transparent',
                          borderRadius: '50%'
                        }}
                      />
                    )}
                  </Avatar>
                  
                  <Box sx={{ 
                    maxWidth: message.type === 'user' ? '70%' : '80%',
                    bgcolor: message.type === 'user' ? currentTheme.palette.primary.light : currentTheme.palette.background.paper,
                    borderRadius: 2,
                    p: 2,
                    color: currentTheme.palette.text.primary
                  }}>
                    {message.isLoading ? (
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        <CircularProgress size={16} />
                        <Typography variant="body2" color="text.secondary">
                          Thinking...
                        </Typography>
                      </Box>
                    ) : (
                      <>
                        <Typography variant="body1" sx={{ mb: 1 }}>
                          {message.content}
                        </Typography>
                        {message.sources && message.sources.length > 0 && (
                          <Typography variant="body2" component="div" sx={{ mb: 1, color: currentTheme.palette.text.secondary }}>
                            <SourceDocs docs={message.sources} label="Sources:" />
                          </Typography>
                        )}
                        
                        <Typography variant="caption" sx={{ display: 'block', mt: 1, color: currentTheme.palette.text.secondary, fontWeight: 500 }}>
                          {message.timestamp.toLocaleTimeString()}
                        </Typography>
                      </>
                    )}
                  </Box>
                </ListItem>
                {index < chatMessages.length - 1 && <Divider sx={{ my: 1 }} />}
              </React.Fragment>
            ))}
          </List>
        )}
      </Paper>

      {/* Input Area */}
      <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
        <TextField
          fullWidth
          multiline
          maxRows={3}
          value={chatInput}
          onChange={(e) => onChatInputChange(e.target.value)}
          onKeyPress={(e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault();
              handleChatSubmit();
            }
          }}
          placeholder="Ask a question and press Enter or click arrow, Shift+Enter for a new line"
          variant="outlined"
          size="small"
          disabled={isQuerying}
          sx={{ 
            '& .MuiOutlinedInput-root': {
              borderRadius: 2,
              backgroundColor: isDarkMode ? currentTheme.palette.background.paper : '#f5f5f5',
              '& fieldset': {
                border: isDarkMode ? 'none' : '1px solid #e0e0e0',
              },
              '&:hover fieldset': {
                border: isDarkMode ? 'none' : '1px solid #1976d2',
              },
              '&.Mui-focused fieldset': {
                border: isDarkMode ? 'none' : '2px solid #1976d2',
              }
            }
          }}
        />
        <IconButton
          color="primary"
          onClick={handleChatSubmit}
          disabled={!chatInput.trim() || isQuerying}
          sx={{ 
            bgcolor: 'primary.main',
            color: 'white',
            '&:hover': { bgcolor: 'primary.dark' },
            '&:disabled': { 
              bgcolor: 'primary.main',
              color: 'white',
              opacity: 0.4
            },
            width: 48,
            height: 48
          }}
        >
          {isQuerying ? <CircularProgress size={20} color="inherit" /> : <SendIcon />}
        </IconButton>
        
        <Button
          variant="outlined"
          size="small"
          onClick={clearChatHistory}
          disabled={chatMessages.length === 0}
          sx={{ ml: 1 }}
        >
          Clear History
        </Button>
      </Box>
    </Box>
  );
};
