// flexible-graphrag-ui/frontend-react/src/components/sources/AlfrescoSourceForm.tsx
import React, { useEffect, useMemo } from 'react';
import { TextField, Box } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface AlfrescoSourceFormProps extends BaseSourceFormProps {
  url: string;
  username: string;
  password: string;
  path: string;
  onUrlChange: (url: string) => void;
  onUsernameChange: (username: string) => void;
  onPasswordChange: (password: string) => void;
  onPathChange: (path: string) => void;
}

export const AlfrescoSourceForm: React.FC<AlfrescoSourceFormProps> = ({
  currentTheme,
  url,
  username,
  password,
  path,
  onUrlChange,
  onUsernameChange,
  onPasswordChange,
  onPathChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const placeholder = useMemo(() => {
    const baseUrl = import.meta.env.VITE_ALFRESCO_BASE_URL || 'http://localhost:8080';
    return `e.g., ${baseUrl}`;
  }, []);

  const isValid = useMemo(() => {
    return path.trim() !== '' && 
           url.trim() !== '' && 
           username.trim() !== '' && 
           password.trim() !== '';
  }, [path, url, username, password]);

  const config = useMemo(() => ({
    url,
    username,
    password,
    path
  }), [url, username, password, path]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  return (
    <BaseSourceForm
      title="Alfresco Repository"
      description="Connect to an Alfresco content management system"
    >
      <TextField
        fullWidth
        label="Alfresco Base URL"
        variant="outlined"
        value={url}
        onChange={(e) => onUrlChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder={placeholder}
      />
      <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
        <TextField
          fullWidth
          label="Username"
          variant="outlined"
          value={username}
          onChange={(e) => onUsernameChange(e.target.value)}
          size="small"
        />
        <TextField
          fullWidth
          label="Password"
          type="password"
          variant="outlined"
          value={password}
          onChange={(e) => onPasswordChange(e.target.value)}
          size="small"
        />
      </Box>
      <TextField
        fullWidth
        label="Path"
        variant="outlined"
        value={path}
        onChange={(e) => onPathChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="e.g., /Sites/example/documentLibrary"
      />
    </BaseSourceForm>
  );
};

// flexible-graphrag-ui/frontend-vue/src/components/sources/AlfrescoSourceForm.vue
<template>
  <BaseSourceForm
    title="Alfresco Repository"
    description="Connect to an Alfresco content management system"
  >
    <v-text-field
      :model-value="url"
      @update:model-value="handleUrlChange"
      label="Alfresco Base URL *"
      variant="outlined"
      class="mb-4"
      :placeholder="placeholder"
      required
    />
    
    <v-row class="mb-4">
      <v-col cols="6">
        <v-text-field
          :model-value="username"
          @update:model-value="handleUsernameChange"
          label="Username *"
          variant="outlined"
          required
        />
      </v-col>
      <v-col cols="6">
        <v-text-field
          :model-value="password"
          @update:model-value="handlePasswordChange"
          label="Password *"
          type="password"
          variant="outlined"
          required
        />
      </v-col>
    </v-row>
    
    <v-text-field
      :model-value="path"
      @update:model-value="handlePathChange"
      label="Path *"
      variant="outlined"
      class="mb-4"
      placeholder="e.g., /Sites/example/documentLibrary"
      hint="Path to the folder containing documents to process"
      persistent-hint
      required
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'AlfrescoSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    url: {
      type: String,
      default: ''
    },
    username: {
      type: String,
      default: 'admin'
    },
    password: {
      type: String,
      default: 'admin'
    },
    path: {
      type: String,
      default: '/Shared/GraphRAG'
    }
  },
  emits: ['update:url', 'update:username', 'update:password', 'update:path', 'configuration-change', 'validation-change'],
  setup(props, { emit }) {
    const placeholder = computed(() => {
      const baseUrl = import.meta.env.VITE_ALFRESCO_BASE_URL || 'http://localhost:8080';
      return `e.g., ${baseUrl}/alfresco`;
    });

    const isValid = computed(() => {
      return props.url.trim() !== '' && 
             props.username.trim() !== '' && 
             props.password.trim() !== '' && 
             props.path.trim() !== '';
    });

    const config = computed(() => ({
      url: props.url,
      username: props.username,
      password: props.password,
      path: props.path
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleUrlChange = (value: string) => {
      emit('update:url', value);
    };

    const handleUsernameChange = (value: string) => {
      emit('update:username', value);
    };

    const handlePasswordChange = (value: string) => {
      emit('update:password', value);
    };

    const handlePathChange = (value: string) => {
      emit('update:path', value);
    };

    return {
      placeholder,
      handleUrlChange,
      handleUsernameChange,
      handlePasswordChange,
      handlePathChange,
    };
  },
});
</script>
