// flexible-graphrag-ui/frontend-react/src/components/sources/AzureBlobSourceForm.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { TextField } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface AzureBlobSourceFormProps extends BaseSourceFormProps {
  connectionString: string;
  containerName: string;
  blobName: string;
  accountName: string;
  accountKey: string;
  onConnectionStringChange: (connectionString: string) => void;
  onContainerNameChange: (containerName: string) => void;
  onBlobNameChange: (blobName: string) => void;
  onAccountNameChange: (accountName: string) => void;
  onAccountKeyChange: (accountKey: string) => void;
}

export const AzureBlobSourceForm: React.FC<AzureBlobSourceFormProps> = ({
  currentTheme,
  connectionString,
  containerName,
  blobName,
  accountName,
  accountKey,
  onConnectionStringChange,
  onContainerNameChange,
  onBlobNameChange,
  onAccountNameChange,
  onAccountKeyChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const [prefix, setPrefix] = useState('');
  const [accountUrl, setAccountUrl] = useState('');

  const isValid = useMemo(() => {
    // Method 1 requires: account_url, container_name, account_name, account_key
    return accountUrl.trim() !== '' && 
           containerName.trim() !== '' && 
           accountName.trim() !== '' && 
           accountKey.trim() !== '';
  }, [accountUrl, containerName, accountName, accountKey]);

  const config = useMemo(() => ({
    // Method 1 (Account Key Authentication) fields
    container_name: containerName,
    account_url: accountUrl,
    blob: blobName || undefined,
    prefix: prefix || undefined,
    account_name: accountName,
    account_key: accountKey
  }), [containerName, accountUrl, blobName, prefix, accountName, accountKey]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  return (
    <BaseSourceForm
      title="Azure Blob Storage"
      description="Connect to Azure Blob Storage using Account Key Authentication (Method 1)"
    >
      <TextField
        fullWidth
        label="Account URL *"
        variant="outlined"
        value={accountUrl}
        onChange={(e) => setAccountUrl(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="https://mystorageaccount.blob.core.windows.net"
        helperText="Azure Storage account URL (required)"
        required
      />
      <TextField
        fullWidth
        label="Container Name *"
        variant="outlined"
        value={containerName}
        onChange={(e) => onContainerNameChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="my-container"
        required
      />
      <TextField
        fullWidth
        label="Blob (Optional)"
        variant="outlined"
        value={blobName}
        onChange={(e) => onBlobNameChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="specific-file.pdf"
        helperText="Optional: specific blob/file name"
      />
      <TextField
        fullWidth
        label="Prefix (Optional)"
        variant="outlined"
        value={prefix}
        onChange={(e) => setPrefix(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="documents/reports/"
        helperText="Optional: folder path prefix within container"
      />
      <TextField
        fullWidth
        label="Account Name *"
        variant="outlined"
        value={accountName}
        onChange={(e) => onAccountNameChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="mystorageaccount"
        helperText="Azure Storage account name (required)"
        required
      />
      <TextField
        fullWidth
        label="Account Key *"
        variant="outlined"
        value={accountKey}
        onChange={(e) => onAccountKeyChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        type="password"
        placeholder="account-key-here"
        helperText="Azure Storage account key (required)"
        required
      />
    </BaseSourceForm>
  );
};

// flexible-graphrag-ui/frontend-vue/src/components/sources/AzureBlobSourceForm.vue
<template>
  <BaseSourceForm
    title="Azure Blob Storage"
    description="Connect to Azure Blob Storage using Account Key Authentication (Method 1)"
  >
    <v-text-field
      v-model="accountUrl"
      label="Account URL *"
      variant="outlined"
      class="mb-2"
      placeholder="https://mystorageaccount.blob.core.windows.net"
      hint="Azure Storage account URL (required)"
      persistent-hint
      required
    />
    
    <v-text-field
      :model-value="containerName"
      @update:model-value="handleContainerNameChange"
      label="Container Name *"
      variant="outlined"
      class="mb-2"
      placeholder="my-container"
      required
    />
    
    <v-text-field
      :model-value="blobName"
      @update:model-value="handleBlobNameChange"
      label="Blob (Optional)"
      variant="outlined"
      class="mb-2"
      placeholder="specific-file.pdf"
      hint="Optional: specific blob/file name"
      persistent-hint
    />
    
    <v-text-field
      v-model="prefix"
      label="Prefix (Optional)"
      variant="outlined"
      class="mb-2"
      placeholder="documents/reports/"
      hint="Optional: folder path prefix within container"
      persistent-hint
    />
    
    <v-text-field
      :model-value="accountName"
      @update:model-value="handleAccountNameChange"
      label="Account Name *"
      variant="outlined"
      class="mb-2"
      placeholder="mystorageaccount"
      hint="Azure Storage account name (required)"
      persistent-hint
      required
    />
    
    <v-text-field
      :model-value="accountKey"
      @update:model-value="handleAccountKeyChange"
      label="Account Key *"
      variant="outlined"
      class="mb-2"
      type="password"
      placeholder="account-key-here"
      hint="Azure Storage account key (required)"
      persistent-hint
      required
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, ref, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'AzureBlobSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    connectionString: {
      type: String,
      default: ''
    },
    containerName: {
      type: String,
      default: ''
    },
    blobName: {
      type: String,
      default: ''
    },
    accountName: {
      type: String,
      default: ''
    },
    accountKey: {
      type: String,
      default: ''
    }
  },
  emits: [
    'update:connectionString', 'update:containerName', 'update:blobName', 
    'update:accountName', 'update:accountKey', 'configuration-change', 'validation-change'
  ],
  setup(props, { emit }) {
    const prefix = ref('');
    const accountUrl = ref('');

    const isValid = computed(() => {
      // Method 1 requires: account_url, container_name, account_name, account_key
      return accountUrl.value.trim() !== '' && 
             props.containerName.trim() !== '' && 
             props.accountName.trim() !== '' && 
             props.accountKey.trim() !== '';
    });

    const config = computed(() => ({
      // Method 1 (Account Key Authentication) fields
      container_name: props.containerName,
      account_url: accountUrl.value,
      blob: props.blobName || undefined,
      prefix: prefix.value || undefined,
      account_name: props.accountName,
      account_key: props.accountKey
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleContainerNameChange = (value: string) => {
      emit('update:containerName', value);
    };

    const handleBlobNameChange = (value: string) => {
      emit('update:blobName', value);
    };

    const handleAccountNameChange = (value: string) => {
      emit('update:accountName', value);
    };

    const handleAccountKeyChange = (value: string) => {
      emit('update:accountKey', value);
    };

    return {
      prefix,
      accountUrl,
      handleContainerNameChange,
      handleBlobNameChange,
      handleAccountNameChange,
      handleAccountKeyChange,
    };
  },
});
</script>
