// flexible-graphrag-ui/frontend-react/src/components/sources/CMISSourceForm.tsx
import React, { useEffect, useMemo } from 'react';
import { TextField, Box } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface CMISSourceFormProps extends BaseSourceFormProps {
  url: string;
  username: string;
  password: string;
  folderPath: string;
  onUrlChange: (url: string) => void;
  onUsernameChange: (username: string) => void;
  onPasswordChange: (password: string) => void;
  onFolderPathChange: (folderPath: string) => void;
}

export const CMISSourceForm: React.FC<CMISSourceFormProps> = ({
  currentTheme,
  url,
  username,
  password,
  folderPath,
  onUrlChange,
  onUsernameChange,
  onPasswordChange,
  onFolderPathChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const placeholder = useMemo(() => {
    const baseUrl = import.meta.env.VITE_CMIS_BASE_URL || 'http://localhost:8080';
    return `e.g., ${baseUrl}/alfresco/api/-default-/public/cmis/versions/1.1/atom`;
  }, []);

  const isValid = useMemo(() => {
    return folderPath.trim() !== '' && 
           url.trim() !== '' && 
           username.trim() !== '' && 
           password.trim() !== '';
  }, [folderPath, url, username, password]);

  const config = useMemo(() => ({
    url,
    username,
    password,
    folder_path: folderPath
  }), [url, username, password, folderPath]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  return (
    <BaseSourceForm
      title="CMIS Repository"
      description="Connect to any CMIS-compliant content management system"
    >
      <TextField
        fullWidth
        label="CMIS Repository URL"
        variant="outlined"
        value={url}
        onChange={(e) => onUrlChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder={placeholder}
      />
      <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
        <TextField
          fullWidth
          label="Username"
          variant="outlined"
          value={username}
          onChange={(e) => onUsernameChange(e.target.value)}
          size="small"
        />
        <TextField
          fullWidth
          label="Password"
          type="password"
          variant="outlined"
          value={password}
          onChange={(e) => onPasswordChange(e.target.value)}
          size="small"
        />
      </Box>
      <TextField
        fullWidth
        label="Folder Path"
        variant="outlined"
        value={folderPath}
        onChange={(e) => onFolderPathChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="e.g., /Sites/example/documentLibrary"
      />
    </BaseSourceForm>
  );
};

// flexible-graphrag-ui/frontend-vue/src/components/sources/CMISSourceForm.vue
<template>
  <BaseSourceForm
    title="CMIS Repository"
    description="Connect to a CMIS-compliant content management system"
  >
    <v-text-field
      :model-value="url"
      @update:model-value="handleUrlChange"
      label="CMIS Repository URL *"
      variant="outlined"
      class="mb-4"
      :placeholder="placeholder"
      required
    />
    
    <v-row class="mb-4">
      <v-col cols="6">
        <v-text-field
          :model-value="username"
          @update:model-value="handleUsernameChange"
          label="Username *"
          variant="outlined"
          required
        />
      </v-col>
      <v-col cols="6">
        <v-text-field
          :model-value="password"
          @update:model-value="handlePasswordChange"
          label="Password *"
          type="password"
          variant="outlined"
          required
        />
      </v-col>
    </v-row>
    
    <v-text-field
      :model-value="folderPath"
      @update:model-value="handleFolderPathChange"
      label="Folder Path *"
      variant="outlined"
      class="mb-4"
      placeholder="e.g., /Sites/example/documentLibrary"
      hint="Path to the folder containing documents to process"
      persistent-hint
      required
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'CMISSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    url: {
      type: String,
      default: ''
    },
    username: {
      type: String,
      default: 'admin'
    },
    password: {
      type: String,
      default: 'admin'
    },
    folderPath: {
      type: String,
      default: '/Shared/GraphRAG'
    }
  },
  emits: ['update:url', 'update:username', 'update:password', 'update:folderPath', 'configuration-change', 'validation-change'],
  setup(props, { emit }) {
    const placeholder = computed(() => {
      const baseUrl = import.meta.env.VITE_CMIS_BASE_URL || 'http://localhost:8080';
      return `e.g., ${baseUrl}/alfresco/api/-default-/public/cmis/versions/1.1/atom`;
    });

    const isValid = computed(() => {
      return props.url.trim() !== '' && 
             props.username.trim() !== '' && 
             props.password.trim() !== '' && 
             props.folderPath.trim() !== '';
    });

    const config = computed(() => ({
      url: props.url,
      username: props.username,
      password: props.password,
      folder_path: props.folderPath
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleUrlChange = (value: string) => {
      emit('update:url', value);
    };

    const handleUsernameChange = (value: string) => {
      emit('update:username', value);
    };

    const handlePasswordChange = (value: string) => {
      emit('update:password', value);
    };

    const handleFolderPathChange = (value: string) => {
      emit('update:folderPath', value);
    };

    return {
      placeholder,
      handleUrlChange,
      handleUsernameChange,
      handlePasswordChange,
      handleFolderPathChange,
    };
  },
});
</script>
