// flexible-graphrag-ui/frontend-angular/src/app/components/sources/cmis-source-form.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { environment } from '../../../environments/environment';

export interface CMISSourceConfig {
  url: string;
  username: string;
  password: string;
  folder_path: string;
}

@Component({
  selector: 'app-cmis-source-form',
  template: `
    <app-base-source-form 
      title="CMIS Repository" 
      description="Connect to a CMIS-compliant content management system">
      
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>CMIS Repository URL *</mat-label>
        <input matInput
               [(ngModel)]="url"
               (ngModelChange)="onUrlChange()"
               [placeholder]="placeholder"
               required />
      </mat-form-field>

      <div class="form-row">
        <mat-form-field appearance="outline" class="half-width">
          <mat-label>Username *</mat-label>
          <input matInput
                 [(ngModel)]="username"
                 (ngModelChange)="onUsernameChange()"
                 required />
        </mat-form-field>

        <mat-form-field appearance="outline" class="half-width">
          <mat-label>Password *</mat-label>
          <input matInput
                 type="password"
                 [(ngModel)]="password"
                 (ngModelChange)="onPasswordChange()"
                 required />
        </mat-form-field>
      </div>

      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Folder Path *</mat-label>
        <input matInput
               [(ngModel)]="folderPath"
               (ngModelChange)="onFolderPathChange()"
               placeholder="e.g., /Sites/example/documentLibrary"
               required />
        <mat-hint>Path to the folder containing documents to process</mat-hint>
      </mat-form-field>
    </app-base-source-form>
  `,
  styles: [`
    .full-width {
      width: 100%;
      margin-bottom: 16px;
    }
    
    .form-row {
      display: flex;
      gap: 16px;
      margin-bottom: 16px;
    }
    
    .half-width {
      flex: 1;
    }
  `],
  standalone: false
})
export class CMISSourceFormComponent implements OnInit, OnDestroy {
  @Input() url: string = '';
  @Input() username: string = 'admin';
  @Input() password: string = 'admin';
  @Input() folderPath: string = '/Shared/GraphRAG';
  
  @Output() urlChange = new EventEmitter<string>();
  @Output() usernameChange = new EventEmitter<string>();
  @Output() passwordChange = new EventEmitter<string>();
  @Output() folderPathChange = new EventEmitter<string>();
  @Output() configurationChange = new EventEmitter<CMISSourceConfig>();
  @Output() validationChange = new EventEmitter<boolean>();

  get placeholder(): string {
    const baseUrl = environment.cmisBaseUrl || 'http://localhost:8080';
    return `e.g., ${baseUrl}/alfresco/api/-default-/public/cmis/versions/1.1/atom`;
  }

  ngOnInit() {
    this.updateValidationAndConfig();
  }

  ngOnDestroy() {
    // Cleanup if needed
  }

  private updateValidationAndConfig() {
    const isValid = this.url.trim() !== '' && 
                   this.username.trim() !== '' && 
                   this.password.trim() !== '' && 
                   this.folderPath.trim() !== '';
    
    const config: CMISSourceConfig = {
      url: this.url,
      username: this.username,
      password: this.password,
      folder_path: this.folderPath
    };
    
    this.validationChange.emit(isValid);
    this.configurationChange.emit(config);
  }

  onUrlChange(): void {
    this.urlChange.emit(this.url);
    this.updateValidationAndConfig();
  }

  onUsernameChange(): void {
    this.usernameChange.emit(this.username);
    this.updateValidationAndConfig();
  }

  onPasswordChange(): void {
    this.passwordChange.emit(this.password);
    this.updateValidationAndConfig();
  }

  onFolderPathChange(): void {
    this.folderPathChange.emit(this.folderPath);
    this.updateValidationAndConfig();
  }
}

// flexible-graphrag-ui/frontend-vue/src/components/sources/CMISSourceForm.vue
<template>
  <BaseSourceForm
    title="CMIS Repository"
    description="Connect to a CMIS-compliant content management system"
  >
    <v-text-field
      :model-value="url"
      @update:model-value="handleUrlChange"
      label="CMIS Repository URL *"
      variant="outlined"
      class="mb-4"
      :placeholder="placeholder"
      required
    />
    
    <v-row class="mb-4">
      <v-col cols="6">
        <v-text-field
          :model-value="username"
          @update:model-value="handleUsernameChange"
          label="Username *"
          variant="outlined"
          required
        />
      </v-col>
      <v-col cols="6">
        <v-text-field
          :model-value="password"
          @update:model-value="handlePasswordChange"
          label="Password *"
          type="password"
          variant="outlined"
          required
        />
      </v-col>
    </v-row>
    
    <v-text-field
      :model-value="folderPath"
      @update:model-value="handleFolderPathChange"
      label="Folder Path *"
      variant="outlined"
      class="mb-4"
      placeholder="e.g., /Sites/example/documentLibrary"
      hint="Path to the folder containing documents to process"
      persistent-hint
      required
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'CMISSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    url: {
      type: String,
      default: ''
    },
    username: {
      type: String,
      default: 'admin'
    },
    password: {
      type: String,
      default: 'admin'
    },
    folderPath: {
      type: String,
      default: '/Shared/GraphRAG'
    }
  },
  emits: ['update:url', 'update:username', 'update:password', 'update:folderPath', 'configuration-change', 'validation-change'],
  setup(props, { emit }) {
    const placeholder = computed(() => {
      const baseUrl = import.meta.env.VITE_CMIS_BASE_URL || 'http://localhost:8080';
      return `e.g., ${baseUrl}/alfresco/api/-default-/public/cmis/versions/1.1/atom`;
    });

    const isValid = computed(() => {
      return props.url.trim() !== '' && 
             props.username.trim() !== '' && 
             props.password.trim() !== '' && 
             props.folderPath.trim() !== '';
    });

    const config = computed(() => ({
      url: props.url,
      username: props.username,
      password: props.password,
      folder_path: props.folderPath
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleUrlChange = (value: string) => {
      emit('update:url', value);
    };

    const handleUsernameChange = (value: string) => {
      emit('update:username', value);
    };

    const handlePasswordChange = (value: string) => {
      emit('update:password', value);
    };

    const handleFolderPathChange = (value: string) => {
      emit('update:folderPath', value);
    };

    return {
      placeholder,
      handleUrlChange,
      handleUsernameChange,
      handlePasswordChange,
      handleFolderPathChange,
    };
  },
});
</script>
