// flexible-graphrag-ui/frontend-react/src/components/sources/GCSSourceForm.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { TextField } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface GCSSourceFormProps extends BaseSourceFormProps {
  bucketName: string;
  credentials: string;
  prefix?: string;
  pubsubSubscription?: string;
  onBucketNameChange: (bucketName: string) => void;
  onCredentialsChange: (credentials: string) => void;
  onPrefixChange?: (prefix: string) => void;
  onPubsubSubscriptionChange?: (subscription: string) => void;
}

export const GCSSourceForm: React.FC<GCSSourceFormProps> = ({
  currentTheme,
  bucketName,
  credentials,
  prefix: initialPrefix = '',
  pubsubSubscription: initialPubsubSubscription = '',
  onBucketNameChange,
  onCredentialsChange,
  onPrefixChange,
  onPubsubSubscriptionChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const [prefix, setPrefix] = useState(initialPrefix);
  const [pubsubSubscription, setPubsubSubscription] = useState(initialPubsubSubscription);

  // Sync local state with props when they change
  useEffect(() => {
    setPrefix(initialPrefix);
  }, [initialPrefix]);

  useEffect(() => {
    setPubsubSubscription(initialPubsubSubscription);
  }, [initialPubsubSubscription]);

  const handlePrefixChange = (value: string) => {
    setPrefix(value);
    if (onPrefixChange) {
      onPrefixChange(value);
    }
  };

  const handlePubsubSubscriptionChange = (value: string) => {
    setPubsubSubscription(value);
    if (onPubsubSubscriptionChange) {
      onPubsubSubscriptionChange(value);
    }
  };

  const isValid = useMemo(() => {
    return bucketName.trim() !== '' && credentials.trim() !== '';
  }, [bucketName, credentials]);

  const config = useMemo(() => ({
    bucket_name: bucketName,
    credentials: credentials,
    prefix: prefix || undefined,
    pubsub_subscription: pubsubSubscription || undefined
  }), [bucketName, credentials, prefix, pubsubSubscription]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  return (
    <BaseSourceForm
      title="Google Cloud Storage"
      description="Connect to Google Cloud Storage buckets"
    >
      <TextField
        fullWidth
        label="Bucket Name"
        variant="outlined"
        value={bucketName}
        onChange={(e) => onBucketNameChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="my-gcs-bucket"
      />
      <TextField
        fullWidth
        label="Prefix/Path (Optional)"
        variant="outlined"
        value={prefix}
        onChange={(e) => handlePrefixChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="sample-docs/"
        helperText="Optional: folder path prefix (e.g., 'sample-docs/' for a specific folder)"
      />
      <TextField
        fullWidth
        label="Service Account Credentials (JSON)"
        variant="outlined"
        value={credentials}
        onChange={(e) => onCredentialsChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        multiline
        rows={3}
        placeholder='{"type": "service_account", "project_id": "...", ...}'
        helperText="Paste your GCS service account JSON credentials (includes project_id)"
      />
      <TextField
        fullWidth
        label="Pub/Sub Subscription (Optional)"
        variant="outlined"
        value={pubsubSubscription}
        onChange={(e) => handlePubsubSubscriptionChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="gcs-notifications-sub"
        helperText="Pub/Sub subscription name for real-time change detection (leave empty for periodic polling)"
      />
    </BaseSourceForm>
  );
};

// flexible-graphrag-ui/frontend-vue/src/components/sources/GCSSourceForm.vue
<template>
  <BaseSourceForm
    title="Google Cloud Storage"
    description="Connect to Google Cloud Storage buckets"
  >
    <v-text-field
      :model-value="bucketName"
      @update:model-value="handleBucketNameChange"
      label="Bucket Name *"
      variant="outlined"
      class="mb-2"
      placeholder="my-gcs-bucket"
      hint="GCS bucket name (required)"
      persistent-hint
      required
    />
    
    <v-text-field
      :model-value="localPrefix"
      @update:model-value="handlePrefixChange"
      label="Prefix (Optional)"
      variant="outlined"
      class="mb-2"
      placeholder="sample-docs/"
      hint="Optional: folder path prefix (e.g., 'sample-docs/' for a specific folder)"
      persistent-hint
    />
    
    <v-textarea
      :model-value="credentials"
      @update:model-value="handleCredentialsChange"
      label="Service Account Credentials (JSON) *"
      variant="outlined"
      class="mb-2"
      placeholder='{"type": "service_account", "project_id": "...", ...}'
      hint="JSON service account key (includes project_id)"
      persistent-hint
      rows="4"
      required
    />
    
    <v-text-field
      :model-value="localPubsubSubscription"
      @update:model-value="handlePubsubSubscriptionChange"
      label="Pub/Sub Subscription (Optional)"
      variant="outlined"
      class="mb-2"
      placeholder="gcs-notifications-sub"
      hint="Pub/Sub subscription name for real-time change detection (leave empty for periodic polling)"
      persistent-hint
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, ref, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'GCSSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    bucketName: {
      type: String,
      default: ''
    },
    credentials: {
      type: String,
      default: ''
    },
    prefix: {
      type: String,
      default: ''
    },
    pubsubSubscription: {
      type: String,
      default: ''
    }
  },
  emits: [
    'update:bucketName', 'update:credentials', 
    'update:prefix', 'update:pubsubSubscription',
    'configuration-change', 'validation-change'
  ],
  setup(props, { emit }) {
    const localPrefix = ref(props.prefix);
    const localPubsubSubscription = ref(props.pubsubSubscription);

    // Sync local state with props
    watch(() => props.prefix, (newVal) => {
      localPrefix.value = newVal;
    });

    watch(() => props.pubsubSubscription, (newVal) => {
      localPubsubSubscription.value = newVal;
    });

    const isValid = computed(() => {
      return props.bucketName.trim() !== '' && 
             props.credentials.trim() !== '';
    });

    const config = computed(() => ({
      bucket_name: props.bucketName,
      credentials: props.credentials,
      prefix: localPrefix.value || undefined,
      pubsub_subscription: localPubsubSubscription.value || undefined
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleBucketNameChange = (value: string) => {
      emit('update:bucketName', value);
    };

    const handleCredentialsChange = (value: string) => {
      emit('update:credentials', value);
    };

    const handlePrefixChange = (value: string) => {
      localPrefix.value = value;
      emit('update:prefix', value);
    };

    const handlePubsubSubscriptionChange = (value: string) => {
      localPubsubSubscription.value = value;
      emit('update:pubsubSubscription', value);
    };

    return {
      localPrefix,
      localPubsubSubscription,
      handleBucketNameChange,
      handleCredentialsChange,
      handlePrefixChange,
      handlePubsubSubscriptionChange,
    };
  },
});
</script>
