// flexible-graphrag-ui/frontend-angular/projects/flexible-graphrag-angular-lib/src/lib/components/sources/google-drive-source-form.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';

export interface GoogleDriveSourceConfig {
  credentials: string;
}

@Component({
  selector: 'app-google-drive-source-form',
  template: `
    <app-base-source-form 
      title="Google Drive" 
      description="Connect to Google Drive using service account credentials">
      
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Service Account Credentials (JSON) *</mat-label>
        <textarea matInput
                  [(ngModel)]="credentials"
                  (ngModelChange)="onCredentialsChange()"
                  placeholder='{"type": "service_account", "project_id": "...", ...}'
                  rows="4"
                  required></textarea>
        <mat-hint>JSON service account key (required)</mat-hint>
      </mat-form-field>
    </app-base-source-form>
  `,
  styles: [`
    .full-width {
      width: 100%;
      margin-bottom: 16px;
    }
  `],
  standalone: false
})
export class GoogleDriveSourceFormComponent implements OnInit, OnDestroy {
  @Input() credentials: string = '';
  
  @Output() credentialsChange = new EventEmitter<string>();
  @Output() configurationChange = new EventEmitter<GoogleDriveSourceConfig>();
  @Output() validationChange = new EventEmitter<boolean>();

  ngOnInit() {
    this.updateValidationAndConfig();
  }

  ngOnDestroy() {
    // Cleanup if needed
  }

  private updateValidationAndConfig() {
    const isValid = this.credentials.trim() !== '';
    
    const config: GoogleDriveSourceConfig = {
      credentials: this.credentials
    };
    
    this.validationChange.emit(isValid);
    this.configurationChange.emit(config);
  }

  onCredentialsChange(): void {
    this.credentialsChange.emit(this.credentials);
    this.updateValidationAndConfig();
  }
}

// flexible-graphrag-ui/frontend-vue/src/components/sources/GoogleDriveSourceForm.vue
<template>
  <BaseSourceForm
    title="Google Drive"
    description="Connect to Google Drive using service account credentials"
  >
    <v-textarea
      :model-value="credentials"
      @update:model-value="handleCredentialsChange"
      label="Service Account Credentials (JSON) *"
      variant="outlined"
      class="mb-2"
      placeholder='{"type": "service_account", "project_id": "...", ...}'
      hint="JSON service account key (required)"
      persistent-hint
      rows="4"
      required
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'GoogleDriveSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    credentials: {
      type: String,
      default: ''
    }
  },
  emits: ['update:credentials', 'configuration-change', 'validation-change'],
  setup(props, { emit }) {
    const isValid = computed(() => {
      return props.credentials.trim() !== '';
    });

    const config = computed(() => ({
      credentials: props.credentials
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleCredentialsChange = (value: string) => {
      emit('update:credentials', value);
    };

    return {
      handleCredentialsChange,
    };
  },
});
</script>
