// flexible-graphrag-ui/frontend-react/src/components/sources/SharePointSourceForm.tsx
import React, { useEffect, useMemo, useState } from 'react';
import { TextField, Box } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface SharePointSourceFormProps extends BaseSourceFormProps {
  siteName: string;
  clientId: string;
  clientSecret: string;
  tenantId: string;
  onSiteNameChange: (siteName: string) => void;  // Changed from onSiteUrlChange
  onClientIdChange: (clientId: string) => void;
  onClientSecretChange: (clientSecret: string) => void;
  onTenantIdChange: (tenantId: string) => void;
}

export const SharePointSourceForm: React.FC<SharePointSourceFormProps> = ({
  currentTheme,
  siteName,  // Changed from siteUrl to siteName
  clientId,
  clientSecret,
  tenantId,
  onSiteNameChange,  // Changed from onSiteUrlChange
  onClientIdChange,
  onClientSecretChange,
  onTenantIdChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const [folderPath, setFolderPath] = useState('');
  const [folderId, setFolderId] = useState('');  // Changed from documentLibrary to folderId
  const [siteId, setSiteId] = useState('');  // Added for Sites.Selected permission

  const isValid = useMemo(() => {
    return siteName.trim() !== '' && clientId.trim() !== '' && clientSecret.trim() !== '' && tenantId.trim() !== '';
  }, [siteName, clientId, clientSecret, tenantId]);

  const config = useMemo(() => ({
    site_name: siteName,
    client_id: clientId,
    client_secret: clientSecret,
    tenant_id: tenantId,
    site_id: siteId || undefined,  // Added for Sites.Selected permission
    folder_path: folderPath || undefined,
    folder_id: folderId || undefined  // Changed from document_library to folder_id
  }), [siteName, clientId, clientSecret, tenantId, siteId, folderPath, folderId]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  return (
    <BaseSourceForm
      title="Microsoft SharePoint"
      description="Connect to SharePoint sites using Azure app registration credentials"
    >
      <TextField
        fullWidth
        label="Site Name *"
        variant="outlined"
        value={siteName}
        onChange={(e) => onSiteNameChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="sitename"
        helperText="SharePoint site name (not full URL, just the site name)"
        required
        autoComplete="off"
      />
      <TextField
        fullWidth
        label="Site ID (Optional)"
        variant="outlined"
        value={siteId}
        onChange={(e) => setSiteId(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="12345678-1234-1234-1234-123456789012"
        helperText="Optional: Site ID for Sites.Selected permission (recommended for security)"
        autoComplete="off"
      />
      <TextField
        fullWidth
        label="Client ID *"
        variant="outlined"
        value={clientId}
        onChange={(e) => onClientIdChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="12345678-1234-1234-1234-123456789012"
        required
      />
      <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
        <TextField
          fullWidth
          label="Client Secret *"
          variant="outlined"
          value={clientSecret}
          onChange={(e) => onClientSecretChange(e.target.value)}
          size="small"
          type="password"
          required
        />
        <TextField
          fullWidth
          label="Tenant ID *"
          variant="outlined"
          value={tenantId}
          onChange={(e) => onTenantIdChange(e.target.value)}
          size="small"
          placeholder="tenant-id"
          required
        />
      </Box>
      <TextField
        fullWidth
        label="Folder ID (Optional)"
        variant="outlined"
        value={folderId}
        onChange={(e) => setFolderId(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="01BYE5RZ6QN6OWWLQZC5FK2GWWDURNZHIL"
        helperText="Optional: specific folder ID (replaces document library)"
        autoComplete="off"
      />
      <TextField
        fullWidth
        label="Folder Path (Optional)"
        variant="outlined"
        value={folderPath}
        onChange={(e) => setFolderPath(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="/Shared Documents/Reports"
        helperText="Optional: specific folder path within site"
        autoComplete="off"
      />
    </BaseSourceForm>
  );
};

// flexible-graphrag-ui/frontend-vue/src/components/sources/SharePointSourceForm.vue
<template>
  <BaseSourceForm
    title="Microsoft SharePoint"
    description="Connect to SharePoint sites using Azure app registration credentials"
  >
    <v-text-field
      :model-value="siteName"
      @update:model-value="handleSiteNameChange"
      label="Site Name *"
      variant="outlined"
      class="mb-2"
      placeholder="sitename"
      hint="SharePoint site name (not full URL, just the site name)"
      persistent-hint
      required
    />
    
    <v-text-field
      v-model="siteId"
      label="Site ID (Optional)"
      variant="outlined"
      class="mb-2"
      placeholder="12345678-1234-1234-1234-123456789012"
      hint="Optional: Site ID for Sites.Selected permission (recommended for security)"
      persistent-hint
    />
    
    <v-text-field
      :model-value="clientId"
      @update:model-value="handleClientIdChange"
      label="Client ID *"
      variant="outlined"
      class="mb-2"
      placeholder="12345678-1234-1234-1234-123456789012"
      hint="Azure app registration client ID (required)"
      persistent-hint
      required
    />
    
    <div class="d-flex ga-2 mb-2">
      <v-text-field
        :model-value="clientSecret"
        @update:model-value="handleClientSecretChange"
        label="Client Secret *"
        variant="outlined"
        type="password"
        placeholder="client-secret-here"
        hint="Azure app registration client secret (required)"
        persistent-hint
        required
      />
      
      <v-text-field
        :model-value="tenantId"
        @update:model-value="handleTenantIdChange"
        label="Tenant ID *"
        variant="outlined"
        placeholder="tenant-id"
        hint="Azure tenant ID (required)"
        persistent-hint
        required
      />
    </div>
    
    <v-text-field
      v-model="folderId"
      label="Folder ID (Optional)"
      variant="outlined"
      class="mb-2"
      placeholder="01BYE5RZ6QN6OWWLQZC5FK2GWWDURNZHIL"
      hint="Optional: specific folder ID (replaces document library)"
      persistent-hint
    />
    
    <v-text-field
      v-model="folderPath"
      label="Folder Path (Optional)"
      variant="outlined"
      class="mb-2"
      placeholder="/Shared Documents/Reports"
      hint="Optional: specific folder path within site"
      persistent-hint
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, ref, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'SharePointSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    siteName: {
      type: String,
      default: ''
    },
    clientId: {
      type: String,
      default: ''
    },
    clientSecret: {
      type: String,
      default: ''
    },
    tenantId: {
      type: String,
      default: ''
    }
  },
  emits: [
    'update:siteName', 
    'update:clientId', 
    'update:clientSecret', 
    'update:tenantId', 
    'configuration-change', 
    'validation-change'
  ],
  setup(props, { emit }) {
    const folderId = ref('');
    const folderPath = ref('');
    const siteId = ref('');

    const isValid = computed(() => {
      return props.siteName.trim() !== '' && 
             props.clientId.trim() !== '' && 
             props.clientSecret.trim() !== '' && 
             props.tenantId.trim() !== '';
    });

    const config = computed(() => ({
      site_name: props.siteName,
      client_id: props.clientId,
      client_secret: props.clientSecret,
      tenant_id: props.tenantId,
      site_id: siteId.value || undefined,
      folder_path: folderPath.value || undefined,
      folder_id: folderId.value || undefined
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleSiteNameChange = (value: string) => {
      emit('update:siteName', value);
    };

    const handleClientIdChange = (value: string) => {
      emit('update:clientId', value);
    };

    const handleClientSecretChange = (value: string) => {
      emit('update:clientSecret', value);
    };

    const handleTenantIdChange = (value: string) => {
      emit('update:tenantId', value);
    };

    return {
      folderId,
      folderPath,
      siteId,
      handleSiteNameChange,
      handleClientIdChange,
      handleClientSecretChange,
      handleTenantIdChange,
    };
  },
});
</script>
