// flexible-graphrag-ui/frontend-angular/src/app/components/sources/web-source-form.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';

export interface WebSourceConfig {
  url: string;
}

@Component({
  selector: 'app-web-source-form',
  template: `
    <app-base-source-form 
      title="Web Page" 
      description="Extract content from any web page">
      
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Website URL</mat-label>
        <input matInput
               [(ngModel)]="url"
               (ngModelChange)="onUrlChange()"
               placeholder="https://example.com"
               required />
        <mat-hint>Enter a valid website URL to extract content from</mat-hint>
      </mat-form-field>
    </app-base-source-form>
  `,
  styles: [`
    .full-width {
      width: 100%;
      margin-bottom: 16px;
    }
  `],
  standalone: false
})
export class WebSourceFormComponent implements OnInit, OnDestroy {
  @Input() url: string = '';
  @Output() urlChange = new EventEmitter<string>();
  @Output() configurationChange = new EventEmitter<WebSourceConfig>();
  @Output() validationChange = new EventEmitter<boolean>();

  ngOnInit() {
    this.updateValidationAndConfig();
  }

  ngOnDestroy() {
    // Cleanup if needed
  }

  private updateValidationAndConfig() {
    const isValid = this.url.trim() !== '' && this.url.startsWith('http');
    const config: WebSourceConfig = {
      url: this.url
    };
    
    this.validationChange.emit(isValid);
    this.configurationChange.emit(config);
  }

  onUrlChange(): void {
    this.urlChange.emit(this.url);
    this.updateValidationAndConfig();
  }
}

// flexible-graphrag-ui/frontend-vue/src/components/sources/WebSourceForm.vue
<template>
  <BaseSourceForm
    title="Web Page"
    description="Extract content from any web page"
  >
    <v-text-field
      :model-value="url"
      @update:model-value="handleUrlChange"
      label="Website URL"
      variant="outlined"
      class="mb-2"
      placeholder="https://example.com"
      hint="Enter a valid website URL to extract content from"
      persistent-hint
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'WebSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    url: {
      type: String,
      default: ''
    }
  },
  emits: ['update:url', 'configuration-change', 'validation-change'],
  setup(props, { emit }) {
    const isValid = computed(() => {
      return props.url.trim() !== '' && props.url.startsWith('http');
    });

    const config = computed(() => ({
      url: props.url
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleUrlChange = (value: string) => {
      emit('update:url', value);
    };

    return {
      handleUrlChange,
    };
  },
});
</script>
