// flexible-graphrag-ui/frontend-angular/src/app/components/sources/youtube-source-form.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';

export interface YouTubeSourceConfig {
  url: string;
  chunk_size_seconds: number;
}

@Component({
  selector: 'app-youtube-source-form',
  template: `
    <app-base-source-form 
      title="YouTube" 
      description="Extract transcripts from YouTube videos">
      
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>YouTube URL</mat-label>
        <input matInput
               [(ngModel)]="url"
               (ngModelChange)="onUrlChange()"
               placeholder="https://www.youtube.com/watch?v=..."
               required />
        <mat-hint>Enter a YouTube video URL to extract transcript from</mat-hint>
      </mat-form-field>
    </app-base-source-form>
  `,
  styles: [`
    .full-width {
      width: 100%;
      margin-bottom: 16px;
    }
  `],
  standalone: false
})
export class YouTubeSourceFormComponent implements OnInit, OnDestroy {
  @Input() url: string = '';
  
  @Output() urlChange = new EventEmitter<string>();
  @Output() configurationChange = new EventEmitter<YouTubeSourceConfig>();
  @Output() validationChange = new EventEmitter<boolean>();

  ngOnInit() {
    this.updateValidationAndConfig();
  }

  ngOnDestroy() {
    // Cleanup if needed
  }

  private updateValidationAndConfig() {
    const isValid = this.url.trim() !== '' && 
                   (this.url.includes('youtube.com/watch') || this.url.includes('youtu.be/'));
    
    const config: YouTubeSourceConfig = {
      url: this.url,
      chunk_size_seconds: 60  // Use default value
    };
    
    this.validationChange.emit(isValid);
    this.configurationChange.emit(config);
  }

  onUrlChange(): void {
    this.urlChange.emit(this.url);
    this.updateValidationAndConfig();
  }
}

// flexible-graphrag-ui/frontend-vue/src/components/sources/YouTubeSourceForm.vue
<template>
  <BaseSourceForm
    title="YouTube"
    description="Extract transcripts from YouTube videos"
  >
    <v-text-field
      :model-value="url"
      @update:model-value="handleUrlChange"
      label="YouTube URL"
      variant="outlined"
      class="mb-2"
      placeholder="https://www.youtube.com/watch?v=..."
      hint="Enter a YouTube video URL to extract transcript from"
      persistent-hint
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'YouTubeSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    url: {
      type: String,
      default: ''
    }
  },
  emits: ['update:url', 'configuration-change', 'validation-change'],
  setup(props, { emit }) {
    const isValid = computed(() => {
      return props.url.trim() !== '' && 
             (props.url.includes('youtube.com/watch') || props.url.includes('youtu.be/'));
    });

    const config = computed(() => ({
      url: props.url,
      chunk_size_seconds: 60  // Use default value
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleUrlChange = (value: string) => {
      emit('update:url', value);
    };

    return {
      handleUrlChange,
    };
  },
});
</script>
