// flexible-graphrag-ui/frontend-react/src/components/sources/YouTubeSourceForm.tsx
import React, { useEffect, useMemo } from 'react';
import { TextField } from '@mui/material';
import { BaseSourceForm, BaseSourceFormProps } from './BaseSourceForm';

interface YouTubeSourceFormProps extends BaseSourceFormProps {
  url: string;
  onUrlChange: (url: string) => void;
}

export const YouTubeSourceForm: React.FC<YouTubeSourceFormProps> = ({
  currentTheme,
  url,
  onUrlChange,
  onConfigurationChange,
  onValidationChange,
}) => {
  const isValid = useMemo(() => {
    return url.trim() !== '' && (url.includes('youtube.com') || url.includes('youtu.be'));
  }, [url]);

  const config = useMemo(() => ({
    url: url,
    chunk_size_seconds: 60  // Default 1 minute
  }), [url]);

  useEffect(() => {
    onValidationChange(isValid);
    onConfigurationChange(config);
  }, [isValid, config, onValidationChange, onConfigurationChange]);

  return (
    <BaseSourceForm
      title="YouTube Video"
      description="Extract transcript from YouTube videos"
    >
      <TextField
        fullWidth
        label="YouTube URL"
        variant="outlined"
        value={url}
        onChange={(e) => onUrlChange(e.target.value)}
        size="small"
        sx={{ mb: 2 }}
        placeholder="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        helperText="Enter a YouTube video URL to extract transcript"
      />
    </BaseSourceForm>
  );
};

// flexible-graphrag-ui/frontend-vue/src/components/sources/YouTubeSourceForm.vue
<template>
  <BaseSourceForm
    title="YouTube"
    description="Extract transcripts from YouTube videos"
  >
    <v-text-field
      :model-value="url"
      @update:model-value="handleUrlChange"
      label="YouTube URL"
      variant="outlined"
      class="mb-2"
      placeholder="https://www.youtube.com/watch?v=..."
      hint="Enter a YouTube video URL to extract transcript from"
      persistent-hint
    />
  </BaseSourceForm>
</template>

<script lang="ts">
import { defineComponent, computed, watch } from 'vue';
import BaseSourceForm from './BaseSourceForm.vue';

export default defineComponent({
  name: 'YouTubeSourceForm',
  components: {
    BaseSourceForm
  },
  props: {
    url: {
      type: String,
      default: ''
    }
  },
  emits: ['update:url', 'configuration-change', 'validation-change'],
  setup(props, { emit }) {
    const isValid = computed(() => {
      return props.url.trim() !== '' && 
             (props.url.includes('youtube.com/watch') || props.url.includes('youtu.be/'));
    });

    const config = computed(() => ({
      url: props.url,
      chunk_size_seconds: 60  // Use default value
    }));

    // Emit validation and configuration changes
    watch([isValid, config], ([newIsValid, newConfig]) => {
      emit('validation-change', newIsValid);
      emit('configuration-change', newConfig);
    }, { immediate: true });

    const handleUrlChange = (value: string) => {
      emit('update:url', value);
    };

    return {
      handleUrlChange,
    };
  },
});
</script>
